// Generated by lsc from complexity.ts

function StringIndexOf(s: string, sub: string): int
  ensures StringIndexOf(s, sub) == -1
       || (0 <= StringIndexOf(s, sub) <= |s| - |sub| && s[StringIndexOf(s, sub)..StringIndexOf(s, sub) + |sub|] == sub)
{
  StringIndexOfFrom(s, sub, 0)
}

function StringIndexOfFrom(s: string, sub: string, from: int): int
  ensures StringIndexOfFrom(s, sub, from) == -1
       || (0 <= StringIndexOfFrom(s, sub, from) <= |s| - |sub|
           && s[StringIndexOfFrom(s, sub, from)..StringIndexOfFrom(s, sub, from) + |sub|] == sub
           && StringIndexOfFrom(s, sub, from) >= from)
{
  StringIndexOfFromN(s, sub, if from < 0 then 0 else from)
}

function StringIndexOfFromN(s: string, sub: string, from: nat): int
  decreases |s| - from
  ensures StringIndexOfFromN(s, sub, from) == -1
       || (from <= StringIndexOfFromN(s, sub, from) <= |s| - |sub|
           && s[StringIndexOfFromN(s, sub, from)..StringIndexOfFromN(s, sub, from) + |sub|] == sub)
{
  if from + |sub| > |s| then -1
  else if s[from..from + |sub|] == sub then from as int
  else StringIndexOfFromN(s, sub, from + 1)
}

function StringTrimLeft(s: string): string
  ensures |StringTrimLeft(s)| <= |s|
  ensures StringTrimLeft(s) == "" || (|StringTrimLeft(s)| > 0 && StringTrimLeft(s)[0] != ' ')
  decreases |s|
{
  if |s| == 0 then ""
  else if s[0] == ' ' then StringTrimLeft(s[1..])
  else s
}

function StringTrimRight(s: string): string
  ensures |StringTrimRight(s)| <= |s|
  decreases |s|
{
  if |s| == 0 then ""
  else if s[|s|-1] == ' ' then StringTrimRight(s[..|s|-1])
  else s
}

function StringTrim(s: string): string
{
  StringTrimRight(StringTrimLeft(s))
}

function countNonBlank(lines: seq<string>): int
  decreases |lines|
{
  if (|lines| == 0) then
    0
  else
    var first := StringTrim(lines[0]);
    var rest := countNonBlank(lines[1..]);
    if (|first| > 0) then
      (rest + 1)
    else
      rest
}

lemma countNonBlank_ensures(lines: seq<string>)
  ensures (countNonBlank(lines) >= 0)
  ensures (countNonBlank(lines) <= |lines|)
{
}

function countPattern(lines: seq<string>, pattern: string): int
  requires (|pattern| > 0)
  decreases |lines|
{
  if (|lines| == 0) then
    0
  else
    var line := lines[0];
    var rest := countPattern(lines[1..], pattern);
    if (StringIndexOf(line, pattern) >= 0) then
      (rest + 1)
    else
      rest
}

lemma countPattern_ensures(lines: seq<string>, pattern: string)
  requires (|pattern| > 0)
  ensures (countPattern(lines, pattern) >= 0)
{
}

function countBranches(line: string): int
{
  var ifBranch := (if ((StringIndexOf(line, "if") >= 0) || (StringIndexOf(line, "if(") >= 0)) then 1 else 0);
  var forBranch := (if ((StringIndexOf(line, "for") >= 0) || (StringIndexOf(line, "for(") >= 0)) then 1 else 0);
  var whileBranch := (if ((StringIndexOf(line, "while") >= 0) || (StringIndexOf(line, "while(") >= 0)) then 1 else 0);
  var caseBranch := (if (StringIndexOf(line, "case ") >= 0) then 1 else 0);
  var catchBranch := (if (StringIndexOf(line, "catch") >= 0) then 1 else 0);
  var andBranch := (if (StringIndexOf(line, "&&") >= 0) then 1 else 0);
  var orBranch := (if (StringIndexOf(line, "||") >= 0) then 1 else 0);
  ((((((ifBranch + forBranch) + whileBranch) + caseBranch) + catchBranch) + andBranch) + orBranch)
}

lemma countBranches_ensures(line: string)
  ensures (countBranches(line) >= 0)
{
}

function estimateComplexity(lines: seq<string>): int
  decreases |lines|
{
  if (|lines| == 0) then
    1
  else
    var branches := countBranches(lines[0]);
    var rest := estimateComplexity(lines[1..]);
    (rest + branches)
}

lemma estimateComplexity_ensures(lines: seq<string>)
  ensures (estimateComplexity(lines) >= 1)
{
}

function nonBlankBounds(lines: seq<string>): bool
{
  true
}

lemma nonBlankBounds_ensures(lines: seq<string>)
  ensures (countNonBlank(lines) >= 0)
  ensures (countNonBlank(lines) <= |lines|)
{
}

function patternNonNegative(lines: seq<string>, pattern: string): bool
  requires (|pattern| > 0)
{
  true
}

lemma patternNonNegative_ensures(lines: seq<string>, pattern: string)
  requires (|pattern| > 0)
  ensures (countPattern(lines, pattern) >= 0)
{
}

function complexityMinimum(lines: seq<string>): bool
{
  true
}

lemma complexityMinimum_ensures(lines: seq<string>)
  ensures (estimateComplexity(lines) >= 1)
{
}
