// Generated by lsc from exec_core.ts

datatype EStep = EStep(reads_: seq<string>, bind: seq<string>)

function contains(xs: seq<string>, y: string): bool
  decreases |xs|
{
  if (|xs| == 0) then
    false
  else
    ((xs[0] == y) || contains(xs[1..], y))
}

function allBound(reads_: seq<string>, bound: seq<string>): bool
  decreases |reads_|
{
  ((|reads_| == 0) || (if !(contains(bound, reads_[0])) then false else allBound(reads_[1..], bound)))
}

function allBinds(steps: seq<EStep>): seq<string>
  decreases |steps|
{
  if (|steps| == 0) then
    []
  else
    (steps[0].bind + allBinds(steps[1..]))
}

function allReadsBound(steps: seq<EStep>, b: seq<string>): bool
  decreases |steps|
{
  ((|steps| == 0) || (if !(allBound(steps[0].reads_, b)) then false else allReadsBound(steps[1..], b)))
}

function okAllBinds(steps: seq<EStep>): bool
{
  allReadsBound(steps, allBinds(steps))
}

function execOk(steps: seq<EStep>, bound: seq<string>): bool
  decreases |steps|
{
  ((|steps| == 0) || (if !(allBound(steps[0].reads_, bound)) then false else execOk(steps[1..], (bound + steps[0].bind))))
}

// ── hand-written theorems + supporting lemmas (proofs; not in the .ts, as in edit.dfy) ──

// Membership is preserved by appending more names.
lemma containsConcat(bound: seq<string>, more: seq<string>, y: string)
  ensures contains(bound, y) ==> contains(bound + more, y)
{
  if |bound| > 0 {
    assert (bound + more)[1..] == bound[1..] + more;
    containsConcat(bound[1..], more, y);
  }
}

// allBound is preserved by appending more names to the bound set.
lemma allBoundConcat(reads_: seq<string>, bound: seq<string>, more: seq<string>)
  ensures allBound(reads_, bound) ==> allBound(reads_, bound + more)
{
  if |reads_| > 0 {
    containsConcat(bound, more, reads_[0]);
    allBoundConcat(reads_[1..], bound, more);
  }
}

// Generalized strengthening: an in-order-resolvable run (from any prior `bound`)
// satisfies the weaker all-binds check. fixIsStrengthening instantiates bound = [].
lemma strengthenGen(steps: seq<EStep>, bound: seq<string>)
  ensures execOk(steps, bound) ==> allReadsBound(steps, bound + allBinds(steps))
{
  if |steps| > 0 {
    var s := steps[0];
    var rest := steps[1..];
    assert allBinds(steps) == s.bind + allBinds(rest);
    assert bound + allBinds(steps) == (bound + s.bind) + allBinds(rest);
    allBoundConcat(s.reads_, bound, allBinds(steps));
    strengthenGen(rest, bound + s.bind);
  }
}

// THEOREM — the old all-binds check passes a forward-ref plan that execution rejects.
lemma forwardRefGap()
  ensures okAllBinds([EStep(["x"], []), EStep([], ["x"])]) == true
  ensures execOk([EStep(["x"], []), EStep([], ["x"])], []) == false
{
}

// THEOREM — the fixed (in-order) check is a strengthening: execOk ==> okAllBinds.
lemma fixIsStrengthening(steps: seq<EStep>)
  ensures execOk(steps, []) ==> okAllBinds(steps)
{
  strengthenGen(steps, []);
  assert [] + allBinds(steps) == allBinds(steps);
}
