// Generated by lsc from edit.ts

datatype Edit = NotFound | Ambiguous | Replaced

function matchesAt(hay: seq<string>, old_: seq<string>): bool
  decreases |old_|
{
  ((|old_| == 0) || (if (|hay| == 0) then false else (if (hay[0] != old_[0]) then false else matchesAt(hay[1..], old_[1..]))))
}

function dropMatch(hay: seq<string>, old_: seq<string>): seq<string>
  decreases |old_|
{
  if (|old_| == 0) then
    hay
  else
    if (|hay| == 0) then
      hay
    else
      dropMatch(hay[1..], old_[1..])
}

function occurs(hay: seq<string>, old_: seq<string>): bool
  decreases |hay|
{
  if (|hay| == 0) then
    false
  else
    (matchesAt(hay, old_) || occurs(hay[1..], old_))
}

function afterFirst(hay: seq<string>, old_: seq<string>): seq<string>
  decreases |hay|
{
  if (|hay| == 0) then
    []
  else
    if matchesAt(hay, old_) then
      dropMatch(hay, old_)
    else
      afterFirst(hay[1..], old_)
}

function replaceFirst(hay: seq<string>, old_: seq<string>, repl: seq<string>): seq<string>
  decreases |hay|
{
  if (|hay| == 0) then
    hay
  else
    if matchesAt(hay, old_) then
      (repl + dropMatch(hay, old_))
    else
      ([hay[0]] + replaceFirst(hay[1..], old_, repl))
}

function manyOcc(hay: seq<string>, old_: seq<string>): bool
{
  (occurs(hay, old_) && occurs(afterFirst(hay, old_), old_))
}

function editFile(content: seq<string>, old_: seq<string>, all: bool): Edit
  requires (|old_| > 0)
{
  if !(occurs(content, old_)) then
    Edit.NotFound
  else
    if (manyOcc(content, old_) && !(all)) then
      Edit.Ambiguous
    else
      Edit.Replaced
}

lemma editFile_ensures(content: seq<string>, old_: seq<string>, all: bool)
  requires (|old_| > 0)
  ensures (editFile(content, old_, all).NotFound? == !(occurs(content, old_)))
  ensures (editFile(content, old_, all).Ambiguous? == (manyOcc(content, old_) && !(all)))
  ensures (editFile(content, old_, all).Replaced? == (occurs(content, old_) && (!(manyOcc(content, old_)) || all)))
{
}

// ── Splice faithfulness (proof additions) ────────────────────────────────────

// The matched prefix is exactly `old`: dropMatch removes it and nothing more.
lemma MatchSplit(hay: seq<string>, old_: seq<string>)
  requires matchesAt(hay, old_)
  ensures old_ + dropMatch(hay, old_) == hay
  decreases |old_|
{
  if |old_| > 0 {
    assert |hay| > 0 && hay[0] == old_[0] && matchesAt(hay[1..], old_[1..]);
    MatchSplit(hay[1..], old_[1..]);
    assert old_ == [old_[0]] + old_[1..];
    assert hay == [hay[0]] + hay[1..];
  }
}

lemma DropMatchLen(hay: seq<string>, old_: seq<string>)
  requires matchesAt(hay, old_)
  ensures |dropMatch(hay, old_)| == |hay| - |old_|
{
  MatchSplit(hay, old_);
}

// E2 — replacing text that does not occur leaves the content unchanged.
lemma E2_NoMatchIdentity(hay: seq<string>, old_: seq<string>, repl: seq<string>)
  requires !occurs(hay, old_)
  ensures replaceFirst(hay, old_, repl) == hay
  decreases |hay|
{
  if |hay| > 0 {
    assert !matchesAt(hay, old_) && !occurs(hay[1..], old_);
    E2_NoMatchIdentity(hay[1..], old_, repl);
    assert hay == [hay[0]] + hay[1..];
  }
}

// E3 — replacing `old` with `old` is a no-op: the splice touches exactly the
// matched span and preserves everything else.
lemma E3_SpliceNoop(hay: seq<string>, old_: seq<string>)
  ensures replaceFirst(hay, old_, old_) == hay
  decreases |hay|
{
  if |hay| > 0 {
    if matchesAt(hay, old_) {
      MatchSplit(hay, old_);
    } else {
      E3_SpliceNoop(hay[1..], old_);
      assert hay == [hay[0]] + hay[1..];
    }
  }
}

// Length law — a single splice changes the length by exactly |repl| - |old|.
lemma E_Len(hay: seq<string>, old_: seq<string>, repl: seq<string>)
  requires occurs(hay, old_)
  ensures |replaceFirst(hay, old_, repl)| == |hay| - |old_| + |repl|
  decreases |hay|
{
  assert |hay| > 0;
  if matchesAt(hay, old_) {
    DropMatchLen(hay, old_);
  } else {
    assert occurs(hay[1..], old_);
    E_Len(hay[1..], old_, repl);
    assert hay == [hay[0]] + hay[1..];
  }
}
