// Generated by lsc from hooks.ts

datatype Option<T> = None | Some(value: T)

datatype Tool = Tool(name: string)

datatype Hook = Hook(tools: Option<seq<Tool>>, removeTools: Option<seq<string>>, pathBased: Option<seq<string>>, autoAllowCwd: Option<seq<string>>, autoAllow: Option<seq<string>>, rejectPrompts: Option<bool>, systemPrompt: Option<string>)

function contains(xs: seq<string>, x: string): bool
  decreases |xs|
{
  if (|xs| == 0) then
    false
  else
    ((xs[0] == x) || contains(xs[1..], x))
}

function hasName(tools: seq<Tool>, name: string): bool
  decreases |tools|
{
  if (|tools| == 0) then
    false
  else
    ((tools[0].name == name) || hasName(tools[1..], name))
}

function dedupTools(acc: seq<Tool>, tools: seq<Tool>, removes: seq<string>): seq<Tool>
  decreases |tools|
{
  if (|tools| == 0) then
    acc
  else
    var t := tools[0];
    var rest := tools[1..];
    if contains(removes, t.name) then
      dedupTools(acc, rest, removes)
    else
      if hasName(acc, t.name) then
        dedupTools(acc, rest, removes)
      else
        dedupTools((acc + [t]), rest, removes)
}

function allTools(defaults: seq<Tool>, hooks: seq<Hook>): seq<Tool>
  decreases |hooks|
{
  if (|hooks| == 0) then
    defaults
  else
    allTools((defaults + (match hooks[0].tools { case Some(i_oc0_val) => i_oc0_val case None => [] })), hooks[1..])
}

function allRemoves(hooks: seq<Hook>): seq<string>
  decreases |hooks|
{
  if (|hooks| == 0) then
    []
  else
    ((match hooks[0].removeTools { case Some(i_oc1_val) => i_oc1_val case None => [] }) + allRemoves(hooks[1..]))
}

function mergeTools(defaults: seq<Tool>, hooks: seq<Hook>): seq<Tool>
{
  dedupTools([], allTools(defaults, hooks), allRemoves(hooks))
}

function flatten(parts: seq<seq<string>>): seq<string>
  decreases |parts|
{
  if (|parts| == 0) then
    []
  else
    (parts[0] + flatten(parts[1..]))
}

function gather(base: seq<string>, parts: seq<seq<string>>): seq<string>
{
  (base + flatten(parts))
}

// ═══════════════════════════════════════════════════════════════════════════
// Surfaced properties (generated from hooks.ts) + their proofs, over the REAL
// mergeTools / gather. A few append/ghost-predicate induction lemmas follow.
// ═══════════════════════════════════════════════════════════════════════════

function removedExcluded(defaults: seq<Tool>, hooks: seq<Hook>, name: string): bool
  requires contains(allRemoves(hooks), name)
{
  true
}

// H1 removal — a removed tool name never survives the merge.
lemma removedExcluded_ensures(defaults: seq<Tool>, hooks: seq<Hook>, name: string)
  requires contains(allRemoves(hooks), name)
  ensures !(hasName(mergeTools(defaults, hooks), name))
{
  if hasName(mergeTools(defaults, hooks), name) {
    hasNameCorrect_ensures(mergeTools(defaults, hooks), name);
    var i :| 0 <= i < |mergeTools(defaults, hooks)| && mergeTools(defaults, hooks)[i].name == name;
    var t := mergeTools(defaults, hooks)[i];
    assert t in mergeTools(defaults, hooks);
    assert mergeTools(defaults, hooks) == dedupTools([], allTools(defaults, hooks), allRemoves(hooks));
    DedupToolsExcludesRemoved([], allTools(defaults, hooks), allRemoves(hooks), t);
  }
}

function distinctMergedNames(defaults: seq<Tool>, hooks: seq<Hook>): bool
{
  true
}

// H2 uniqueness (the dedup fix) — merged tool names are pairwise distinct.
lemma distinctMergedNames_ensures(defaults: seq<Tool>, hooks: seq<Hook>)
  ensures forall i: int, j: int :: ((0 <= i) ==> (i < j) ==> (j < |mergeTools(defaults, hooks)|) ==> (mergeTools(defaults, hooks)[i].name != mergeTools(defaults, hooks)[j].name))
{
  assert mergeTools(defaults, hooks) == dedupTools([], allTools(defaults, hooks), allRemoves(hooks));
  DedupToolsDistinct([], allTools(defaults, hooks), allRemoves(hooks));
  assert distinctNames(mergeTools(defaults, hooks));
}

function coverage(defaults: seq<Tool>, hooks: seq<Hook>, name: string): bool
  requires hasName(allTools(defaults, hooks), name)
  requires !(contains(allRemoves(hooks), name))
{
  true
}

// coverage — a kept (present, non-removed) name is preserved by the merge.
lemma coverage_ensures(defaults: seq<Tool>, hooks: seq<Hook>, name: string)
  requires hasName(allTools(defaults, hooks), name)
  requires !(contains(allRemoves(hooks), name))
  ensures hasName(mergeTools(defaults, hooks), name)
{
  DedupToolsCovers([], allTools(defaults, hooks), allRemoves(hooks), name);
}

function gatherMembership(base: seq<string>, parts: seq<seq<string>>, x: string): bool
{
  true
}

// H3 order-independence — gather membership is exactly base ∪ contributions.
lemma gatherMembership_ensures(base: seq<string>, parts: seq<seq<string>>, x: string)
  ensures (contains(gather(base, parts), x) == (contains(base, x) || exists i: int :: (((0 <= i) && (i < |parts|)) && contains(parts[i], x))))
{
  flattenMembership_ensures(parts, x);
  containsCorrect_ensures(gather(base, parts), x);
  containsCorrect_ensures(base, x);
  forall i | 0 <= i < |parts|
    ensures contains(parts[i], x) <==> x in parts[i]
  {
    containsCorrect_ensures(parts[i], x);
  }
}

function gatherGrows(base: seq<string>, parts: seq<seq<string>>, x: string): bool
  requires contains(base, x)
{
  true
}

// H4 additivity — gather only ever grows the base.
lemma gatherGrows_ensures(base: seq<string>, parts: seq<seq<string>>, x: string)
  requires contains(base, x)
  ensures contains(gather(base, parts), x)
{
  containsCorrect_ensures(base, x);
  containsCorrect_ensures(gather(base, parts), x);
}

function containsCorrect(xs: seq<string>, x: string): bool
  decreases |xs|
{
  true
}

// `contains` decides string membership exactly.
lemma containsCorrect_ensures(xs: seq<string>, x: string)
  ensures (contains(xs, x) == (x in xs))
  decreases |xs|
{
  if |xs| == 0 {
  } else {
    containsCorrect_ensures(xs[1..], x);
  }
}

function hasNameCorrect(tools: seq<Tool>, name: string): bool
  decreases |tools|
{
  true
}

// `hasName` decides name-membership exactly.
lemma hasNameCorrect_ensures(tools: seq<Tool>, name: string)
  ensures (hasName(tools, name) == exists i: int :: (((0 <= i) && (i < |tools|)) && (tools[i].name == name)))
  decreases |tools|
{
  if |tools| == 0 {
  } else {
    hasNameCorrect_ensures(tools[1..], name);
  }
}

function flattenMembership(parts: seq<seq<string>>, x: string): bool
  decreases |parts|
{
  true
}

// A name is in the flattened contributions iff it is in some part.
lemma flattenMembership_ensures(parts: seq<seq<string>>, x: string)
  ensures ((x in flatten(parts)) == exists i: int :: (((0 <= i) && (i < |parts|)) && (x in parts[i])))
  decreases |parts|
{
  if |parts| == 0 {
  } else {
    flattenMembership_ensures(parts[1..], x);
    if x in flatten(parts) && x !in parts[0] {
      assert x in flatten(parts[1..]);
      var j :| 0 <= j < |parts[1..]| && x in parts[1..][j];
      assert parts[1..][j] == parts[j + 1];
    }
    forall i | 1 <= i < |parts| && x in parts[i]
      ensures x in flatten(parts[1..])
    {
      assert parts[1..][i - 1] == parts[i];
    }
  }
}

function gatherCommutes(base: seq<string>, p: seq<string>, q: seq<string>, x: string): bool
{
  true
}

// H3 corollary — swapping two hook groups yields the same gather membership.
lemma gatherCommutes_ensures(base: seq<string>, p: seq<string>, q: seq<string>, x: string)
  ensures ((x in gather(base, [p, q])) == (x in gather(base, [q, p])))
{
  gatherMembership_ensures(base, [p, q], x);
  gatherMembership_ensures(base, [q, p], x);
  containsCorrect_ensures(gather(base, [p, q]), x);
  containsCorrect_ensures(gather(base, [q, p]), x);
  assert [p, q][0] == p && [p, q][1] == q;
  assert [q, p][0] == q && [q, p][1] == p;
}

// ── append- / ghost-predicate induction lemmas (kept in .dfy) ──────────────────

predicate distinctNames(ts: seq<Tool>) {
  forall i, j :: 0 <= i < j < |ts| ==> ts[i].name != ts[j].name
}

lemma HasNameAppend(tools: seq<Tool>, t: Tool, name: string)
  ensures hasName(tools, name) ==> hasName(tools + [t], name)
  decreases |tools|
{
  if |tools| == 0 {
  } else {
    HasNameAppend(tools[1..], t, name);
    assert (tools + [t])[0] == tools[0];
    assert (tools + [t])[1..] == tools[1..] + [t];
  }
}

lemma DedupToolsExcludesRemoved(acc: seq<Tool>, tools: seq<Tool>, removes: seq<string>, t: Tool)
  requires forall u :: u in acc ==> !contains(removes, u.name)
  ensures t in dedupTools(acc, tools, removes) ==> !contains(removes, t.name)
  decreases |tools|
{
  if |tools| == 0 {
  } else {
    var t0 := tools[0];
    if contains(removes, t0.name) {
      DedupToolsExcludesRemoved(acc, tools[1..], removes, t);
    } else if hasName(acc, t0.name) {
      DedupToolsExcludesRemoved(acc, tools[1..], removes, t);
    } else {
      assert forall u :: u in acc + [t0] ==> !contains(removes, u.name);
      DedupToolsExcludesRemoved(acc + [t0], tools[1..], removes, t);
    }
  }
}

lemma DedupToolsDistinct(acc: seq<Tool>, tools: seq<Tool>, removes: seq<string>)
  requires distinctNames(acc)
  ensures distinctNames(dedupTools(acc, tools, removes))
  decreases |tools|
{
  if |tools| == 0 {
  } else {
    var t0 := tools[0];
    if contains(removes, t0.name) {
      DedupToolsDistinct(acc, tools[1..], removes);
    } else if hasName(acc, t0.name) {
      DedupToolsDistinct(acc, tools[1..], removes);
    } else {
      hasNameCorrect_ensures(acc, t0.name);
      assert distinctNames(acc + [t0]);
      DedupToolsDistinct(acc + [t0], tools[1..], removes);
    }
  }
}

lemma DedupToolsAccMono(acc: seq<Tool>, tools: seq<Tool>, removes: seq<string>, name: string)
  requires hasName(acc, name)
  ensures hasName(dedupTools(acc, tools, removes), name)
  decreases |tools|
{
  if |tools| == 0 {
  } else {
    var t0 := tools[0];
    if contains(removes, t0.name) {
      DedupToolsAccMono(acc, tools[1..], removes, name);
    } else if hasName(acc, t0.name) {
      DedupToolsAccMono(acc, tools[1..], removes, name);
    } else {
      HasNameAppend(acc, t0, name);
      DedupToolsAccMono(acc + [t0], tools[1..], removes, name);
    }
  }
}

lemma DedupToolsCovers(acc: seq<Tool>, tools: seq<Tool>, removes: seq<string>, name: string)
  requires hasName(tools, name)
  requires !contains(removes, name)
  ensures hasName(dedupTools(acc, tools, removes), name)
  decreases |tools|
{
  var t0 := tools[0];
  if contains(removes, t0.name) {
    assert t0.name != name;
    assert hasName(tools[1..], name);
    DedupToolsCovers(acc, tools[1..], removes, name);
  } else if hasName(acc, t0.name) {
    if t0.name == name {
      DedupToolsAccMono(acc, tools[1..], removes, name);
    } else {
      assert hasName(tools[1..], name);
      DedupToolsCovers(acc, tools[1..], removes, name);
    }
  } else if t0.name == name {
    hasNameCorrect_ensures(acc + [t0], name);
    assert (acc + [t0])[|acc|] == t0;
    DedupToolsAccMono(acc + [t0], tools[1..], removes, name);
  } else {
    assert hasName(tools[1..], name);
    DedupToolsCovers(acc + [t0], tools[1..], removes, name);
  }
}
