// Generated by lsc from hooks.ts

datatype Option<T> = None | Some(value: T)

datatype Tool = Tool(name: string)

datatype Hook = Hook(tools: Option<seq<Tool>>, removeTools: Option<seq<string>>, pathBased: Option<seq<string>>, autoAllowCwd: Option<seq<string>>, autoAllow: Option<seq<string>>, rejectPrompts: Option<bool>, systemPrompt: Option<string>)

function contains(xs: seq<string>, x: string): bool
  decreases |xs|
{
  if (|xs| == 0) then
    false
  else
    ((xs[0] == x) || contains(xs[1..], x))
}

function hasName(tools: seq<Tool>, name: string): bool
  decreases |tools|
{
  if (|tools| == 0) then
    false
  else
    ((tools[0].name == name) || hasName(tools[1..], name))
}

function dedupTools(acc: seq<Tool>, tools: seq<Tool>, removes: seq<string>): seq<Tool>
  decreases |tools|
{
  if (|tools| == 0) then
    acc
  else
    var t := tools[0];
    var rest := tools[1..];
    if contains(removes, t.name) then
      dedupTools(acc, rest, removes)
    else
      if hasName(acc, t.name) then
        dedupTools(acc, rest, removes)
      else
        dedupTools((acc + [t]), rest, removes)
}

function allTools(defaults: seq<Tool>, hooks: seq<Hook>): seq<Tool>
  decreases |hooks|
{
  if (|hooks| == 0) then
    defaults
  else
    allTools((defaults + (match hooks[0].tools { case Some(i_oc0_val) => i_oc0_val case None => [] })), hooks[1..])
}

function allRemoves(hooks: seq<Hook>): seq<string>
  decreases |hooks|
{
  if (|hooks| == 0) then
    []
  else
    ((match hooks[0].removeTools { case Some(i_oc1_val) => i_oc1_val case None => [] }) + allRemoves(hooks[1..]))
}

function mergeTools(defaults: seq<Tool>, hooks: seq<Hook>): seq<Tool>
{
  dedupTools([], allTools(defaults, hooks), allRemoves(hooks))
}

function flatten(parts: seq<seq<string>>): seq<string>
  decreases |parts|
{
  if (|parts| == 0) then
    []
  else
    (parts[0] + flatten(parts[1..]))
}

function gather(base: seq<string>, parts: seq<seq<string>>): seq<string>
{
  (base + flatten(parts))
}

// ═══════════════════════════════════════════════════════════════════════════
// Proof additions (added in .dfy, additions-only over .dfy.gen).
// Properties are stated over the REAL mergeTools(seq<Tool>, seq<Hook>).
// ═══════════════════════════════════════════════════════════════════════════

predicate distinctNames(ts: seq<Tool>) {
  forall i, j :: 0 <= i < j < |ts| ==> ts[i].name != ts[j].name
}

lemma ContainsCorrect(xs: seq<string>, x: string)
  ensures contains(xs, x) <==> x in xs
  decreases |xs|
{
  if |xs| == 0 {
  } else {
    ContainsCorrect(xs[1..], x);
  }
}

lemma HasNameCorrect(tools: seq<Tool>, name: string)
  ensures hasName(tools, name) <==> exists i :: 0 <= i < |tools| && tools[i].name == name
  decreases |tools|
{
  if |tools| == 0 {
  } else {
    HasNameCorrect(tools[1..], name);
  }
}

lemma HasNameAppend(tools: seq<Tool>, t: Tool, name: string)
  ensures hasName(tools, name) ==> hasName(tools + [t], name)
  decreases |tools|
{
  if |tools| == 0 {
  } else {
    HasNameAppend(tools[1..], t, name);
    assert (tools + [t])[0] == tools[0];
    assert (tools + [t])[1..] == tools[1..] + [t];
  }
}

// ── H1: no removed name survives the merge ───────────────────────────────────

lemma DedupToolsExcludesRemoved(acc: seq<Tool>, tools: seq<Tool>, removes: seq<string>, t: Tool)
  requires forall u :: u in acc ==> !contains(removes, u.name)
  ensures t in dedupTools(acc, tools, removes) ==> !contains(removes, t.name)
  decreases |tools|
{
  if |tools| == 0 {
  } else {
    var t0 := tools[0];
    if contains(removes, t0.name) {
      DedupToolsExcludesRemoved(acc, tools[1..], removes, t);
    } else if hasName(acc, t0.name) {
      DedupToolsExcludesRemoved(acc, tools[1..], removes, t);
    } else {
      assert forall u :: u in acc + [t0] ==> !contains(removes, u.name);
      DedupToolsExcludesRemoved(acc + [t0], tools[1..], removes, t);
    }
  }
}

lemma H1_RemovedExcluded(defaults: seq<Tool>, hooks: seq<Hook>, t: Tool)
  ensures t in mergeTools(defaults, hooks) ==> !contains(allRemoves(hooks), t.name)
{
  DedupToolsExcludesRemoved([], allTools(defaults, hooks), allRemoves(hooks), t);
}

// ── H2: result tool names are distinct (the dedup fix) ───────────────────────

lemma DedupToolsDistinct(acc: seq<Tool>, tools: seq<Tool>, removes: seq<string>)
  requires distinctNames(acc)
  ensures distinctNames(dedupTools(acc, tools, removes))
  decreases |tools|
{
  if |tools| == 0 {
  } else {
    var t0 := tools[0];
    if contains(removes, t0.name) {
      DedupToolsDistinct(acc, tools[1..], removes);
    } else if hasName(acc, t0.name) {
      DedupToolsDistinct(acc, tools[1..], removes);
    } else {
      HasNameCorrect(acc, t0.name);
      assert distinctNames(acc + [t0]);
      DedupToolsDistinct(acc + [t0], tools[1..], removes);
    }
  }
}

lemma H2_DistinctNames(defaults: seq<Tool>, hooks: seq<Hook>)
  ensures distinctNames(mergeTools(defaults, hooks))
{
  DedupToolsDistinct([], allTools(defaults, hooks), allRemoves(hooks));
}

// ── coverage: a kept (non-removed) name is preserved ─────────────────────────

lemma DedupToolsAccMono(acc: seq<Tool>, tools: seq<Tool>, removes: seq<string>, name: string)
  requires hasName(acc, name)
  ensures hasName(dedupTools(acc, tools, removes), name)
  decreases |tools|
{
  if |tools| == 0 {
  } else {
    var t0 := tools[0];
    if contains(removes, t0.name) {
      DedupToolsAccMono(acc, tools[1..], removes, name);
    } else if hasName(acc, t0.name) {
      DedupToolsAccMono(acc, tools[1..], removes, name);
    } else {
      HasNameAppend(acc, t0, name);
      DedupToolsAccMono(acc + [t0], tools[1..], removes, name);
    }
  }
}

lemma DedupToolsCovers(acc: seq<Tool>, tools: seq<Tool>, removes: seq<string>, name: string)
  requires hasName(tools, name)
  requires !contains(removes, name)
  ensures hasName(dedupTools(acc, tools, removes), name)
  decreases |tools|
{
  var t0 := tools[0];
  if contains(removes, t0.name) {
    assert t0.name != name;
    assert hasName(tools[1..], name);
    DedupToolsCovers(acc, tools[1..], removes, name);
  } else if hasName(acc, t0.name) {
    if t0.name == name {
      DedupToolsAccMono(acc, tools[1..], removes, name);
    } else {
      assert hasName(tools[1..], name);
      DedupToolsCovers(acc, tools[1..], removes, name);
    }
  } else if t0.name == name {
    HasNameCorrect(acc + [t0], name);
    assert (acc + [t0])[|acc|] == t0;
    DedupToolsAccMono(acc + [t0], tools[1..], removes, name);
  } else {
    assert hasName(tools[1..], name);
    DedupToolsCovers(acc + [t0], tools[1..], removes, name);
  }
}

lemma Coverage(defaults: seq<Tool>, hooks: seq<Hook>, name: string)
  requires hasName(allTools(defaults, hooks), name)
  requires !contains(allRemoves(hooks), name)
  ensures hasName(mergeTools(defaults, hooks), name)
{
  DedupToolsCovers([], allTools(defaults, hooks), allRemoves(hooks), name);
}

// ── H3 / H4: permission gather (order-independence, additivity) ──────────────

lemma FlattenMembership(parts: seq<seq<string>>, x: string)
  ensures x in flatten(parts) <==> exists i :: 0 <= i < |parts| && x in parts[i]
  decreases |parts|
{
  if |parts| == 0 {
  } else {
    FlattenMembership(parts[1..], x);
    if x in flatten(parts) && x !in parts[0] {
      assert x in flatten(parts[1..]);
      var j :| 0 <= j < |parts[1..]| && x in parts[1..][j];
      assert parts[1..][j] == parts[j + 1];
    }
    forall i | 1 <= i < |parts| && x in parts[i]
      ensures x in flatten(parts[1..])
    {
      assert parts[1..][i - 1] == parts[i];
    }
  }
}

// H3: gather membership = base ∪ contributions — independent of hook order.
lemma H3_GatherMembership(base: seq<string>, parts: seq<seq<string>>, x: string)
  ensures x in gather(base, parts) <==> (x in base || exists i :: 0 <= i < |parts| && x in parts[i])
{
  FlattenMembership(parts, x);
}

// H4: gather only grows the base set (additivity).
lemma H4_GatherGrows(base: seq<string>, parts: seq<seq<string>>, x: string)
  ensures x in base ==> x in gather(base, parts)
{
}

// H3 corollary: swapping two hook groups yields the same membership.
lemma H3_Commutes(base: seq<string>, p: seq<string>, q: seq<string>, x: string)
  ensures (x in gather(base, [p, q])) <==> (x in gather(base, [q, p]))
{
  H3_GatherMembership(base, [p, q], x);
  H3_GatherMembership(base, [q, p], x);
  assert [p, q][0] == p && [p, q][1] == q;
  assert [q, p][0] == q && [q, p][1] == p;
}
