// Generated by lsc from merge.ts

function contains(xs: seq<string>, x: string): bool
  decreases |xs|
{
  if (|xs| == 0) then
    false
  else
    ((xs[0] == x) || contains(xs[1..], x))
}

function removeAll(names: seq<string>, removes: seq<string>): seq<string>
  decreases |names|
{
  if (|names| == 0) then
    []
  else
    var rest := removeAll(names[1..], removes);
    if contains(removes, names[0]) then
      rest
    else
      ([names[0]] + rest)
}

function dedupFrom(acc: seq<string>, names: seq<string>): seq<string>
  decreases |names|
{
  if (|names| == 0) then
    acc
  else
    if contains(acc, names[0]) then
      dedupFrom(acc, names[1..])
    else
      dedupFrom((acc + [names[0]]), names[1..])
}

function dedup(names: seq<string>): seq<string>
{
  dedupFrom([], names)
}

function mergeNames(names: seq<string>, removes: seq<string>): seq<string>
{
  dedup(removeAll(names, removes))
}

function flatten(parts: seq<seq<string>>): seq<string>
  decreases |parts|
{
  if (|parts| == 0) then
    []
  else
    (parts[0] + flatten(parts[1..]))
}

function gather(base: seq<string>, parts: seq<seq<string>>): seq<string>
{
  (base + flatten(parts))
}

// ═══════════════════════════════════════════════════════════════════════════
// Proof additions (added in .dfy, additions-only over .dfy.gen).
// ═══════════════════════════════════════════════════════════════════════════

predicate distinct(xs: seq<string>) {
  forall i, j :: 0 <= i < j < |xs| ==> xs[i] != xs[j]
}

lemma ContainsCorrect(xs: seq<string>, x: string)
  ensures contains(xs, x) <==> x in xs
  decreases |xs|
{
  if |xs| == 0 {
  } else {
    ContainsCorrect(xs[1..], x);
  }
}

// ── H1: removed names are excluded ───────────────────────────────────────────

lemma RemoveAllSubset(names: seq<string>, removes: seq<string>, x: string)
  ensures x in removeAll(names, removes) ==> x in names
  decreases |names|
{
  if |names| == 0 {
  } else {
    RemoveAllSubset(names[1..], removes, x);
  }
}

lemma RemoveAllExcludes(names: seq<string>, removes: seq<string>, x: string)
  ensures x in removeAll(names, removes) ==> !contains(removes, x)
  decreases |names|
{
  if |names| == 0 {
  } else {
    RemoveAllExcludes(names[1..], removes, x);
  }
}

lemma RemoveAllKeeps(names: seq<string>, removes: seq<string>, x: string)
  requires x in names
  requires !contains(removes, x)
  ensures x in removeAll(names, removes)
  decreases |names|
{
  if |names| == 0 {
  } else if names[0] == x {
  } else {
    assert x in names[1..];
    RemoveAllKeeps(names[1..], removes, x);
  }
}

// ── dedup membership and distinctness (H2) ───────────────────────────────────

lemma DedupFromMembership(acc: seq<string>, names: seq<string>, x: string)
  ensures x in dedupFrom(acc, names) <==> (x in acc || x in names)
  decreases |names|
{
  if |names| == 0 {
  } else if contains(acc, names[0]) {
    ContainsCorrect(acc, names[0]);
    DedupFromMembership(acc, names[1..], x);
  } else {
    DedupFromMembership(acc + [names[0]], names[1..], x);
  }
}

lemma DedupFromDistinct(acc: seq<string>, names: seq<string>)
  requires distinct(acc)
  ensures distinct(dedupFrom(acc, names))
  decreases |names|
{
  if |names| == 0 {
  } else if contains(acc, names[0]) {
    DedupFromDistinct(acc, names[1..]);
  } else {
    ContainsCorrect(acc, names[0]);
    assert names[0] !in acc;
    assert distinct(acc + [names[0]]);
    DedupFromDistinct(acc + [names[0]], names[1..]);
  }
}

// ── H1 / H2 / coverage headlines ─────────────────────────────────────────────

// H1: no removed name survives the merge.
lemma H1_RemovedExcluded(names: seq<string>, removes: seq<string>, x: string)
  ensures x in mergeNames(names, removes) ==> !contains(removes, x)
{
  DedupFromMembership([], removeAll(names, removes), x);
  RemoveAllExcludes(names, removes, x);
}

// H2: the merged tool-name list is duplicate-free (the dedup fix).
lemma H2_Distinct(names: seq<string>, removes: seq<string>)
  ensures distinct(mergeNames(names, removes))
{
  DedupFromDistinct([], removeAll(names, removes));
}

// Coverage: a kept (non-removed) name is preserved.
lemma Coverage(names: seq<string>, removes: seq<string>, x: string)
  requires x in names
  requires !contains(removes, x)
  ensures x in mergeNames(names, removes)
{
  RemoveAllKeeps(names, removes, x);
  DedupFromMembership([], removeAll(names, removes), x);
}

// ── H3 / H4: permission gather (order-independence, additivity) ──────────────

lemma FlattenMembership(parts: seq<seq<string>>, x: string)
  ensures x in flatten(parts) <==> exists i :: 0 <= i < |parts| && x in parts[i]
  decreases |parts|
{
  if |parts| == 0 {
  } else {
    FlattenMembership(parts[1..], x);
    if x in flatten(parts) && x !in parts[0] {
      // x came from the tail; lift the tail witness by one index
      assert x in flatten(parts[1..]);
      var j :| 0 <= j < |parts[1..]| && x in parts[1..][j];
      assert parts[1..][j] == parts[j + 1];
    }
    forall i | 1 <= i < |parts| && x in parts[i]
      ensures x in flatten(parts[1..])
    {
      assert parts[1..][i - 1] == parts[i];
    }
  }
}

// H3: gather membership = base ∪ contributions — independent of hook order.
lemma H3_GatherMembership(base: seq<string>, parts: seq<seq<string>>, x: string)
  ensures x in gather(base, parts) <==> (x in base || exists i :: 0 <= i < |parts| && x in parts[i])
{
  FlattenMembership(parts, x);
}

// H4: gather only grows the base set (additivity).
lemma H4_GatherGrows(base: seq<string>, parts: seq<seq<string>>, x: string)
  ensures x in base ==> x in gather(base, parts)
{
}

// H3 corollary: swapping two hook groups yields the same membership.
lemma H3_Commutes(base: seq<string>, p: seq<string>, q: seq<string>, x: string)
  ensures (x in gather(base, [p, q])) <==> (x in gather(base, [q, p]))
{
  H3_GatherMembership(base, [p, q], x);
  H3_GatherMembership(base, [q, p], x);
  assert [p, q][0] == p && [p, q][1] == q;
  assert [q, p][0] == q && [q, p][1] == p;
}
