// Generated by lsc from permissions.ts

datatype Outcome = Allow | Deny | Prompt

datatype PathGrant = PathGrant(tool: string, segs: seq<string>)

datatype PermState = PermState(autoAllow: set<string>, autoAllowCwd: set<string>, allowedTools: set<string>, allowedBashCommands: set<string>, allowedPaths: seq<PathGrant>, allowAll: bool, rejectPrompts: bool)

datatype Req = bash(command: string) | path(tool: string, segs: seq<string>, absolute: bool) | other(tool: string)

function seqEq(a: seq<string>, b: seq<string>): bool
{
  if (|a| != |b|) then
    false
  else
    ((|a| == 0) || (if (a[0] != b[0]) then false else seqEq(a[1..], b[1..])))
}

function normalizeFrom(acc: seq<string>, segs: seq<string>): seq<string>
  decreases |segs|
{
  if (|segs| == 0) then
    acc
  else
    var s := segs[0];
    var rest := segs[1..];
    if (s == "..") then
      normalizeFrom(acc[0..(if (|acc| > 0) then (|acc| - 1) else 0)], rest)
    else
      if ((s == "") || (s == ".")) then
        normalizeFrom(acc, rest)
      else
        normalizeFrom((acc + [s]), rest)
}

function normalize(segs: seq<string>): seq<string>
{
  normalizeFrom([], segs)
}

function resolvePath(cwd: seq<string>, segs: seq<string>, absolute: bool): seq<string>
{
  if absolute then
    normalize(segs)
  else
    normalize((cwd + segs))
}

function isPrefix(base: seq<string>, p: seq<string>): bool
{
  ((|base| == 0) || (if (|p| == 0) then false else (if (base[0] != p[0]) then false else isPrefix(base[1..], p[1..]))))
}

function isWithin(base: seq<string>, p: seq<string>): bool
{
  isPrefix(base, p)
}

function pathGranted(grants: seq<PathGrant>, tool: string, resolved: seq<string>): bool
{
  if (|grants| == 0) then
    false
  else
    var g := grants[0];
    (((g.tool == tool) && seqEq(g.segs, resolved)) || pathGranted(grants[1..], tool, resolved))
}

function isAllowed(st: PermState, cwd: seq<string>, req: Req): bool
{
  (st.allowAll || (match req { case bash(i_req_command) => (("bash" in st.autoAllow) || (i_req_command in st.allowedBashCommands)) case path(i_req_tool, i_req_segs, i_req_absolute) => ((i_req_tool in st.autoAllow) || (var resolved := resolvePath(cwd, i_req_segs, i_req_absolute); (pathGranted(st.allowedPaths, i_req_tool, resolved) || ((i_req_tool in st.autoAllowCwd) && isWithin(cwd, resolved))))) case other(i_req_tool) => ((i_req_tool in st.autoAllow) || (i_req_tool in st.allowedTools)) }))
}

function decide(st: PermState, cwd: seq<string>, req: Req): Outcome
{
  if isAllowed(st, cwd, req) then
    Outcome.Allow
  else
    if st.rejectPrompts then
      Outcome.Deny
    else
      Outcome.Prompt
}

lemma decide_ensures(st: PermState, cwd: seq<string>, req: Req)
  ensures (decide(st, cwd, req).Allow? == isAllowed(st, cwd, req))
  ensures (st.rejectPrompts ==> (!decide(st, cwd, req).Prompt?))
{
}

function autoGrantImpliesWithin(st: PermState, cwd: seq<string>, req: Req): bool
  requires req.path?
  requires !(st.allowAll)
  requires !((req.tool in st.autoAllow))
  requires !(pathGranted(st.allowedPaths, req.tool, resolvePath(cwd, req.segs, req.absolute)))
  requires isAllowed(st, cwd, req)
{
  true
}

lemma autoGrantImpliesWithin_ensures(st: PermState, cwd: seq<string>, req: Req)
  requires req.path?
  requires !(st.allowAll)
  requires !((req.tool in st.autoAllow))
  requires !(pathGranted(st.allowedPaths, req.tool, resolvePath(cwd, req.segs, req.absolute)))
  requires isAllowed(st, cwd, req)
  ensures isWithin(cwd, resolvePath(cwd, req.segs, req.absolute))
{
}

function noEscape(st: PermState, cwd: seq<string>, req: Req): bool
  requires req.path?
  requires !(st.allowAll)
  requires !((req.tool in st.autoAllow))
  requires !(pathGranted(st.allowedPaths, req.tool, resolvePath(cwd, req.segs, req.absolute)))
  requires !(isWithin(cwd, resolvePath(cwd, req.segs, req.absolute)))
{
  true
}

lemma noEscape_ensures(st: PermState, cwd: seq<string>, req: Req)
  requires req.path?
  requires !(st.allowAll)
  requires !((req.tool in st.autoAllow))
  requires !(pathGranted(st.allowedPaths, req.tool, resolvePath(cwd, req.segs, req.absolute)))
  requires !(isWithin(cwd, resolvePath(cwd, req.segs, req.absolute)))
  ensures !(isAllowed(st, cwd, req))
{
}

function grantMonotone(st: PermState, st2: PermState, cwd: seq<string>, req: Req): bool
  requires (st2.allowAll == st.allowAll)
  requires (st2.allowedPaths == st.allowedPaths)
  requires (st.autoAllow <= st2.autoAllow)
  requires (st.autoAllowCwd <= st2.autoAllowCwd)
  requires (st.allowedTools <= st2.allowedTools)
  requires (st.allowedBashCommands <= st2.allowedBashCommands)
  requires isAllowed(st, cwd, req)
{
  true
}

lemma grantMonotone_ensures(st: PermState, st2: PermState, cwd: seq<string>, req: Req)
  requires (st2.allowAll == st.allowAll)
  requires (st2.allowedPaths == st.allowedPaths)
  requires (st.autoAllow <= st2.autoAllow)
  requires (st.autoAllowCwd <= st2.autoAllowCwd)
  requires (st.allowedTools <= st2.allowedTools)
  requires (st.allowedBashCommands <= st2.allowedBashCommands)
  requires isAllowed(st, cwd, req)
  ensures isAllowed(st2, cwd, req)
{
}

function allowAllGrantsEverything(st: PermState, cwd: seq<string>, req: Req): bool
  requires st.allowAll
{
  true
}

lemma allowAllGrantsEverything_ensures(st: PermState, cwd: seq<string>, req: Req)
  requires st.allowAll
  ensures isAllowed(st, cwd, req)
{
}

function rejectIsDenyOnly(st: PermState, st2: PermState, cwd: seq<string>, req: Req): Outcome
  requires st2.rejectPrompts
  requires (st2.allowAll == st.allowAll)
  requires (st2.autoAllow == st.autoAllow)
  requires (st2.autoAllowCwd == st.autoAllowCwd)
  requires (st2.allowedTools == st.allowedTools)
  requires (st2.allowedBashCommands == st.allowedBashCommands)
  requires (st2.allowedPaths == st.allowedPaths)
{
  decide(st2, cwd, req)
}

lemma rejectIsDenyOnly_ensures(st: PermState, st2: PermState, cwd: seq<string>, req: Req)
  requires st2.rejectPrompts
  requires (st2.allowAll == st.allowAll)
  requires (st2.autoAllow == st.autoAllow)
  requires (st2.autoAllowCwd == st.autoAllowCwd)
  requires (st2.allowedTools == st.allowedTools)
  requires (st2.allowedBashCommands == st.allowedBashCommands)
  requires (st2.allowedPaths == st.allowedPaths)
  ensures (rejectIsDenyOnly(st, st2, cwd, req).Allow? == isAllowed(st, cwd, req))
  ensures (!rejectIsDenyOnly(st, st2, cwd, req).Prompt?)
{
}

// ═══════════════════════════════════════════════════════════════════════════
// .dfy-only helpers — statements //@ specs cannot express (list append, {:fuel}).
// The TS carriers above state the headline properties; these reach the rest.
// ═══════════════════════════════════════════════════════════════════════════

// Concrete witness for P2: ../../x from cwd a/b resolves to [x], outside a/b —
// so the escape that noEscape rules out is genuinely reachable.
lemma {:fuel normalizeFrom, 7, 8} P2_EscapeWitness()
  ensures resolvePath(["a", "b"], ["..", "..", "x"], false) == ["x"]
  ensures !isWithin(["a", "b"], resolvePath(["a", "b"], ["..", "..", "x"], false))
{
}

// Appending a grant preserves existing per-path coverage (needs list append).
lemma PathGrantedAppendMonotone(grants: seq<PathGrant>, g: PathGrant, tool: string, resolved: seq<string>)
  ensures pathGranted(grants, tool, resolved) ==> pathGranted(grants + [g], tool, resolved)
  decreases |grants|
{
  if |grants| == 0 {
  } else {
    PathGrantedAppendMonotone(grants[1..], g, tool, resolved);
    assert (grants + [g])[0] == grants[0];
    assert (grants + [g])[1..] == grants[1..] + [g];
  }
}

// P3, per-path case: adding a per-path grant never revokes an existing Allow.
// (The set-channel cases are grantMonotone above; this one needs list append.)
lemma P3_GrantPathMonotone(st: PermState, cwd: seq<string>, req: Req, g: PathGrant)
  requires decide(st, cwd, req).Allow?
  ensures decide(st.(allowedPaths := st.allowedPaths + [g]), cwd, req).Allow?
{
  match req {
    case path(tool, segs, absolute) =>
      PathGrantedAppendMonotone(st.allowedPaths, g, tool, resolvePath(cwd, segs, absolute));
    case bash(_) =>
    case other(_) =>
  }
}

function grantFor(st: PermState, cwd: seq<string>, req: Req): PermState
{
  match req {
    case bash(i_req_command) =>
      st.(allowedBashCommands := (st.allowedBashCommands + {i_req_command}))
    case path(i_req_tool, i_req_segs, i_req_absolute) =>
      st.(allowedPaths := (st.allowedPaths + [PathGrant(i_req_tool, resolvePath(cwd, i_req_segs, i_req_absolute))]))
    case other(i_req_tool) =>
      st.(allowedTools := (st.allowedTools + {i_req_tool}))
  }
}

lemma grantFor_ensures(st: PermState, cwd: seq<string>, req: Req)
  ensures isAllowed(grantFor(st, cwd, req), cwd, req)
  ensures (grantFor(st, cwd, req).rejectPrompts == st.rejectPrompts)
  ensures (grantFor(st, cwd, req).autoAllow == st.autoAllow)
  ensures (grantFor(st, cwd, req).autoAllowCwd == st.autoAllowCwd)
  ensures (grantFor(st, cwd, req).allowAll == st.allowAll)
{
  match req {
    case path(tool, segs, absolute) =>
      PathGrantedAppendHit(st.allowedPaths, tool, resolvePath(cwd, segs, absolute));
    case bash(_) =>
    case other(_) =>
  }
}

function grantAll(st: PermState, cwd: seq<string>, req: Req): PermState
{
  st.(allowAll := true)
}

lemma grantAll_ensures(st: PermState, cwd: seq<string>, req: Req)
  ensures isAllowed(grantAll(st, cwd, req), cwd, req)
  ensures (grantAll(st, cwd, req).rejectPrompts == st.rejectPrompts)
{
}

function grantPreservesAllowed(st: PermState, cwd: seq<string>, req: Req, pcwd: seq<string>, prior: Req): bool
  requires isAllowed(st, pcwd, prior)
{
  true
}

lemma grantPreservesAllowed_ensures(st: PermState, cwd: seq<string>, req: Req, pcwd: seq<string>, prior: Req)
  requires isAllowed(st, pcwd, prior)
  ensures isAllowed(grantFor(st, cwd, req), pcwd, prior)
{
  match req {
    case path(tool, segs, absolute) =>
      P3_GrantPathMonotone(st, pcwd, prior, PathGrant(tool, resolvePath(cwd, segs, absolute)));
    case bash(_) =>
      grantMonotone_ensures(st, grantFor(st, cwd, req), pcwd, prior);
    case other(_) =>
      grantMonotone_ensures(st, grantFor(st, cwd, req), pcwd, prior);
  }
}

// ── .dfy-only helpers for the grant builders ─────────────────────────────────

// seqEq is reflexive (the structural equality used by pathGranted).
lemma SeqEqRefl(a: seq<string>)
  ensures seqEq(a, a)
  decreases |a|
{
  if |a| == 0 {
  } else {
    SeqEqRefl(a[1..]);
  }
}

// The grant just appended covers exactly the (tool, resolved path) it records.
lemma PathGrantedAppendHit(grants: seq<PathGrant>, tool: string, resolved: seq<string>)
  ensures pathGranted(grants + [PathGrant(tool, resolved)], tool, resolved)
  decreases |grants|
{
  if |grants| == 0 {
    assert grants + [PathGrant(tool, resolved)] == [PathGrant(tool, resolved)];
    SeqEqRefl(resolved);
  } else {
    PathGrantedAppendHit(grants[1..], tool, resolved);
    assert (grants + [PathGrant(tool, resolved)])[0] == grants[0];
    assert (grants + [PathGrant(tool, resolved)])[1..] == grants[1..] + [PathGrant(tool, resolved)];
  }
}
