// Generated by lsc from permissions.ts

datatype Outcome = Allow | Deny | Prompt

datatype PathGrant = PathGrant(tool: string, segs: seq<string>)

datatype PermState = PermState(autoAllow: set<string>, autoAllowCwd: set<string>, allowedTools: set<string>, allowedBashCommands: set<string>, allowedPaths: seq<PathGrant>, allowAll: bool, rejectPrompts: bool)

datatype Req = bash(command: string) | path(tool: string, segs: seq<string>, absolute: bool) | other(tool: string)

function seqEq(a: seq<string>, b: seq<string>): bool
{
  if (|a| != |b|) then
    false
  else
    ((|a| == 0) || (if (a[0] != b[0]) then false else seqEq(a[1..], b[1..])))
}

function normalizeFrom(acc: seq<string>, segs: seq<string>): seq<string>
  decreases |segs|
{
  if (|segs| == 0) then
    acc
  else
    var s := segs[0];
    var rest := segs[1..];
    if (s == "..") then
      normalizeFrom(acc[0..(if (|acc| > 0) then (|acc| - 1) else 0)], rest)
    else
      if ((s == "") || (s == ".")) then
        normalizeFrom(acc, rest)
      else
        normalizeFrom((acc + [s]), rest)
}

function normalize(segs: seq<string>): seq<string>
{
  normalizeFrom([], segs)
}

function resolvePath(cwd: seq<string>, segs: seq<string>, absolute: bool): seq<string>
{
  if absolute then
    normalize(segs)
  else
    normalize((cwd + segs))
}

function isPrefix(base: seq<string>, p: seq<string>): bool
{
  ((|base| == 0) || (if (|p| == 0) then false else (if (base[0] != p[0]) then false else isPrefix(base[1..], p[1..]))))
}

function isWithin(base: seq<string>, p: seq<string>): bool
{
  isPrefix(base, p)
}

function pathGranted(grants: seq<PathGrant>, tool: string, resolved: seq<string>): bool
{
  if (|grants| == 0) then
    false
  else
    var g := grants[0];
    (((g.tool == tool) && seqEq(g.segs, resolved)) || pathGranted(grants[1..], tool, resolved))
}

function isAllowed(st: PermState, cwd: seq<string>, req: Req): bool
{
  (st.allowAll || (match req { case bash(i_req_command) => (("bash" in st.autoAllow) || (i_req_command in st.allowedBashCommands)) case path(i_req_tool, i_req_segs, i_req_absolute) => ((i_req_tool in st.autoAllow) || (var resolved := resolvePath(cwd, i_req_segs, i_req_absolute); (pathGranted(st.allowedPaths, i_req_tool, resolved) || ((i_req_tool in st.autoAllowCwd) && isWithin(cwd, resolved))))) case other(i_req_tool) => ((i_req_tool in st.autoAllow) || (i_req_tool in st.allowedTools)) }))
}

function decide(st: PermState, cwd: seq<string>, req: Req): Outcome
{
  if isAllowed(st, cwd, req) then
    Outcome.Allow
  else
    if st.rejectPrompts then
      Outcome.Deny
    else
      Outcome.Prompt
}

lemma decide_ensures(st: PermState, cwd: seq<string>, req: Req)
  ensures (decide(st, cwd, req).Allow? == isAllowed(st, cwd, req))
{
}

// ═══════════════════════════════════════════════════════════════════════════
// Proof additions (added in .dfy, additions-only over .dfy.gen).
// P1 soundness is decide_ensures above (auto-discharged).
// ═══════════════════════════════════════════════════════════════════════════

// ── P2: path-traversal containment (the headline) ───────────────────────────

// Concrete witness: ../../x from cwd a/b resolves to [x], which is outside a/b.
lemma {:fuel normalizeFrom, 7, 8} P2_EscapeWitness()
  ensures resolvePath(["a", "b"], ["..", "..", "x"], false) == ["x"]
  ensures !isWithin(["a", "b"], resolvePath(["a", "b"], ["..", "..", "x"], false))
{
}

// Any auto-grant of a path tool — with no blanket allow, no autoAllow, and no
// explicit per-path grant — implies the resolved path is contained within cwd.
// i.e. auto-allow-in-cwd can NEVER reach outside cwd.
lemma P2_AutoGrantImpliesWithin(st: PermState, cwd: seq<string>, tool: string, segs: seq<string>, absolute: bool)
  requires !st.allowAll
  requires tool !in st.autoAllow
  requires !pathGranted(st.allowedPaths, tool, resolvePath(cwd, segs, absolute))
  requires decide(st, cwd, path(tool, segs, absolute)).Allow?
  ensures isWithin(cwd, resolvePath(cwd, segs, absolute))
{
}

// Dual: a path that escapes cwd, with no other grant, is never allowed.
lemma P2_NoEscape(st: PermState, cwd: seq<string>, tool: string, segs: seq<string>, absolute: bool)
  requires !st.allowAll
  requires tool !in st.autoAllow
  requires !pathGranted(st.allowedPaths, tool, resolvePath(cwd, segs, absolute))
  requires !isWithin(cwd, resolvePath(cwd, segs, absolute))
  ensures decide(st, cwd, path(tool, segs, absolute)) != Allow
{
}

// ── P3: grant monotonicity ───────────────────────────────────────────────────

lemma PathGrantedAppendMonotone(grants: seq<PathGrant>, g: PathGrant, tool: string, resolved: seq<string>)
  ensures pathGranted(grants, tool, resolved) ==> pathGranted(grants + [g], tool, resolved)
  decreases |grants|
{
  if |grants| == 0 {
  } else {
    PathGrantedAppendMonotone(grants[1..], g, tool, resolved);
    assert (grants + [g])[0] == grants[0];
    assert (grants + [g])[1..] == grants[1..] + [g];
  }
}

// Adding an exact-command grant never revokes an existing Allow.
lemma P3_GrantBashMonotone(st: PermState, cwd: seq<string>, req: Req, cmd: string)
  requires decide(st, cwd, req).Allow?
  ensures decide(st.(allowedBashCommands := st.allowedBashCommands + {cmd}), cwd, req).Allow?
{
}

// Adding a per-path grant never revokes an existing Allow.
lemma P3_GrantPathMonotone(st: PermState, cwd: seq<string>, req: Req, g: PathGrant)
  requires decide(st, cwd, req).Allow?
  ensures decide(st.(allowedPaths := st.allowedPaths + [g]), cwd, req).Allow?
{
  match req {
    case path(tool, segs, absolute) =>
      PathGrantedAppendMonotone(st.allowedPaths, g, tool, resolvePath(cwd, segs, absolute));
    case bash(_) =>
    case other(_) =>
  }
}

// Enabling allow-all grants everything.
lemma P3_AllowAllGrantsEverything(st: PermState, cwd: seq<string>, req: Req)
  ensures decide(st.(allowAll := true), cwd, req).Allow?
{
}

// ── P4: rejectPrompts is deny-only ───────────────────────────────────────────

// Enabling rejectPrompts never creates a new Allow (it only rewrites Prompt -> Deny).
lemma P4_RejectIsDenyOnly(st: PermState, cwd: seq<string>, req: Req)
  ensures decide(st.(rejectPrompts := true), cwd, req).Allow? == decide(st, cwd, req).Allow?
  ensures !decide(st.(rejectPrompts := true), cwd, req).Prompt?
{
}
