// Generated by lsc from session.ts

function {:axiom} wellFormed(msgs: seq<TMsg>): bool

function {:axiom} pairs(calls: seq<TToolCall>, results: seq<TToolResult>): bool

function {:axiom} pairsTo(calls: seq<TToolCall>, results: seq<TToolResult>): bool

function {:axiom} headOk(m: TMsg): bool

function {:axiom} initialMsgs(): seq<TMsg>
  ensures wellFormed(initialMsgs())
  ensures (|initialMsgs()| == 0)

function {:axiom} decide(st: PermState, cwd: seq<string>, req: Req): Outcome
  ensures (decide(st, cwd, req).Allow? == isAllowed(st, cwd, req))
  ensures (st.rejectPrompts ==> (!decide(st, cwd, req).Prompt?))

function {:axiom} appendAnsweredBlock(msgs: seq<TMsg>, calls: seq<TToolCall>, results: seq<TToolResult>): seq<TMsg>
  requires wellFormed(msgs)
  requires (|calls| > 0)
  requires pairs(calls, results)
  ensures wellFormed(appendAnsweredBlock(msgs, calls, results))
  ensures (|appendAnsweredBlock(msgs, calls, results)| == (|msgs| + 2))

function {:axiom} pushResult(calls: seq<TToolCall>, done: seq<TToolResult>, isError: bool): seq<TToolResult>
  requires pairsTo(calls, done)
  requires (|done| < |calls|)
  ensures pairsTo(calls, pushResult(calls, done, isError))
  ensures (|pushResult(calls, done, isError)| == (|done| + 1))
  ensures ((|pushResult(calls, done, isError)| == |calls|) ==> pairs(calls, pushResult(calls, done, isError)))

function {:axiom} findCut(msgs: seq<TMsg>, keepRecent: int): int
  requires (0 <= keepRecent)
  ensures ((0 <= findCut(msgs, keepRecent)) && (findCut(msgs, keepRecent) <= |msgs|))
  ensures ((findCut(msgs, keepRecent) == |msgs|) || headOk(msgs[findCut(msgs, keepRecent)]))

function {:axiom} appendUserMsg(msgs: seq<TMsg>): seq<TMsg>
  requires wellFormed(msgs)
  ensures wellFormed(appendUserMsg(msgs))
  ensures (|appendUserMsg(msgs)| == (|msgs| + 1))

function {:axiom} appendAssistantDone(msgs: seq<TMsg>): seq<TMsg>
  requires wellFormed(msgs)
  ensures wellFormed(appendAssistantDone(msgs))
  ensures (|appendAssistantDone(msgs)| == (|msgs| + 1))

function {:axiom} startResults(calls: seq<TToolCall>): seq<TToolResult>
  ensures pairsTo(calls, startResults(calls))
  ensures (|startResults(calls)| == 0)

function {:axiom} grantFor(st: PermState, cwd: seq<string>, req: Req): PermState
  ensures isAllowed(grantFor(st, cwd, req), cwd, req)
  ensures (grantFor(st, cwd, req).rejectPrompts == st.rejectPrompts)
  ensures (grantFor(st, cwd, req).autoAllow == st.autoAllow)
  ensures (grantFor(st, cwd, req).autoAllowCwd == st.autoAllowCwd)
  ensures (grantFor(st, cwd, req).allowAll == st.allowAll)

function {:axiom} grantAll(st: PermState, cwd: seq<string>, req: Req): PermState
  ensures isAllowed(grantAll(st, cwd, req), cwd, req)
  ensures (grantAll(st, cwd, req).rejectPrompts == st.rejectPrompts)

function {:axiom} fillRest(calls: seq<TToolCall>, done: seq<TToolResult>): seq<TToolResult>
  requires (|done| <= |calls|)
  ensures (pairsTo(calls, done) ==> pairs(calls, fillRest(calls, done)))

function {:axiom} compact(msgs: seq<TMsg>, c: int): seq<TMsg>
  requires ((0 <= c) && (c <= |msgs|))
  ensures (wellFormed(msgs) ==> ((c == |msgs|) || headOk(msgs[c])) ==> wellFormed(compact(msgs, c)))
  ensures (|compact(msgs, c)| == ((|msgs| - c) + 1))

function {:axiom} isAllowed(st: PermState, cwd: seq<string>, req: Req): bool

datatype SCall = SCall(id: string, name: string, req: Req, known: bool, noPerm: bool, argsOk: bool)

datatype Answer = yes | no | always | all

datatype SEvent = userInput | compactRequest(keep: int) | providerReply(calls: seq<SCall>, contextTokens: int) | providerInterrupted | toolDone(isError: bool) | promptAnswer(answer: Answer) | batchInterrupted | summaryReady(ok: bool)

datatype SCommand = callProvider | execTool(call: SCall) | askUser(call: SCall) | skipTool(call: SCall, reason: Verdict) | summarize(cut: int)

datatype SPhase = idle | awaitingProvider | toolBatch(calls: seq<SCall>, done: seq<TToolResult>) | awaitingPrompt(calls: seq<SCall>, done: seq<TToolResult>) | awaitingSummary(cut: int)

datatype Session = Session(msgs: seq<TMsg>, perms: PermState, cwd: seq<string>, phase: SPhase, turns: int, maxTurns: int, compactKeep: int, autoCompactAt: int, lastContextTokens: int)

datatype StepOut = StepOut(st: Session, cmds: seq<SCommand>)

datatype Verdict = exec | prompt | skipUnknown | skipDenied | skipMissingArgs

datatype TToolResult = TToolResult(toolCallId: string, isError: bool)

datatype TToolCall = TToolCall(id: string, name: string)

datatype Req = bash(command: string) | path(tool: string, segs: seq<string>, absolute: bool) | other(tool: string)

datatype Outcome = Allow | Deny | Prompt

datatype TMsg = user | assistant(toolCalls: seq<TToolCall>) | tool(toolResults: seq<TToolResult>)

datatype PermState = PermState(autoAllow: set<string>, autoAllowCwd: set<string>, allowedTools: set<string>, allowedBashCommands: set<string>, allowedPaths: seq<PathGrant>, allowAll: bool, rejectPrompts: bool)

datatype PathGrant = PathGrant(tool: string, segs: seq<string>)

function phIdle(): SPhase
{
  SPhase.idle
}

function phAwaitingProvider(): SPhase
{
  SPhase.awaitingProvider
}

function phToolBatch(calls: seq<SCall>, done: seq<TToolResult>): SPhase
{
  toolBatch(calls, done)
}

function phAwaitingPrompt(calls: seq<SCall>, done: seq<TToolResult>): SPhase
{
  awaitingPrompt(calls, done)
}

function phAwaitingSummary(cut: int): SPhase
{
  awaitingSummary(cut)
}

function cmdCallProvider(): SCommand
{
  SCommand.callProvider
}

function cmdExecTool(call: SCall): SCommand
{
  execTool(call)
}

function cmdAskUser(call: SCall): SCommand
{
  askUser(call)
}

function cmdSkipTool(call: SCall, reason: Verdict): SCommand
{
  skipTool(call, reason)
}

function cmdSummarize(cut: int): SCommand
{
  summarize(cut)
}

function anchorTCall(c: TToolCall): TToolCall
{
  c
}

function anchorReq(req: Req): Req
{
  req
}

function anchorOutcome(o: Outcome): Outcome
{
  o
}

function toTCall(c: SCall): TToolCall
{
  TToolCall(c.id, c.name)
}

function projectCalls(calls: seq<SCall>): seq<TToolCall>
  decreases |calls|
  // hand-added (discharged by the recursion itself): the projection preserves
  // length, so batch facts stated over projectCalls transfer to the SCall list.
  ensures |projectCalls(calls)| == |calls|
{
  if (|calls| == 0) then
    []
  else
    ([toTCall(calls[0])] + projectCalls(calls[1..]))
}

lemma projectCalls_ensures(calls: seq<SCall>)
  ensures (|projectCalls(calls)| == |calls|)
{
}

function wellFormedModel(msgs: seq<TMsg>): bool
{
  wellFormed(msgs)
}

function pairsModel(calls: seq<TToolCall>, results: seq<TToolResult>): bool
{
  pairs(calls, results)
}

function inv(st: Session): bool
{
  var ph := st.phase;
  if (ph.toolBatch? || ph.awaitingPrompt?) then
    (((wellFormed(st.msgs) && (|ph.calls| > 0)) && (|ph.done| < |ph.calls|)) && pairsTo(projectCalls(ph.calls), ph.done))
  else
    match ph {
      case awaitingSummary(i_ph_cut) =>
        (((wellFormed(st.msgs) && (0 < i_ph_cut)) && (i_ph_cut <= |st.msgs|)) && ((i_ph_cut == |st.msgs|) || headOk(st.msgs[i_ph_cut])))
      case _ =>
        wellFormed(st.msgs)
    }
}

function initialSession(perms: PermState, cwd: seq<string>, maxTurns: int, compactKeep: int, autoCompactAt: int): Session
{
  Session(initialMsgs(), perms, cwd, phIdle(), 0, maxTurns, compactKeep, autoCompactAt, 0)
}

lemma initialSession_ensures(perms: PermState, cwd: seq<string>, maxTurns: int, compactKeep: int, autoCompactAt: int)
  ensures inv(initialSession(perms, cwd, maxTurns, compactKeep, autoCompactAt))
{
}

function verdictFor(st: Session, c: SCall): Verdict
{
  if !(c.known) then
    Verdict.skipUnknown
  else
    if (c.noPerm || decide(st.perms, st.cwd, c.req).Allow?) then
      if c.argsOk then
        Verdict.exec
      else
        Verdict.skipMissingArgs
    else
      if decide(st.perms, st.cwd, c.req).Deny? then
        Verdict.skipDenied
      else
        Verdict.prompt
}

lemma verdictFor_ensures(st: Session, c: SCall)
  ensures (verdictFor(st, c).exec? ==> (c.noPerm || isAllowed(st.perms, st.cwd, c.req)))
  ensures (verdictFor(st, c).prompt? ==> (!(c.noPerm) && !(isAllowed(st.perms, st.cwd, c.req))))
  ensures (st.perms.rejectPrompts ==> (!verdictFor(st, c).prompt?))
{
}

function requestProvider(st: Session): StepOut
  requires wellFormed(st.msgs)
{
  if ((st.maxTurns > 0) && (st.turns >= st.maxTurns)) then
    StepOut(st.(phase := phIdle()), [])
  else
    StepOut(st.(turns := (st.turns + 1), phase := phAwaitingProvider()), [cmdCallProvider()])
}

function finishBatch(st: Session, calls: seq<SCall>, done: seq<TToolResult>, stopped: bool): StepOut
  requires wellFormed(st.msgs)
  requires (|calls| > 0)
  requires pairs(projectCalls(calls), done)
{
  var msgs2 := appendAnsweredBlock(st.msgs, projectCalls(calls), done);
  if stopped then
    StepOut(st.(msgs := msgs2, phase := phIdle()), [])
  else
    requestProvider(st.(msgs := msgs2))
}

function advance(st: Session, calls: seq<SCall>, done: seq<TToolResult>): StepOut
  requires wellFormed(st.msgs)
  requires (|calls| > 0)
  requires (|done| < |calls|)
  requires pairsTo(projectCalls(calls), done)
  decreases (|calls| - |done|)
{
  var c := calls[|done|];
  var v := verdictFor(st, c);
  if v.exec? then
    StepOut(st.(phase := phToolBatch(calls, done)), [cmdExecTool(c)])
  else
    if v.prompt? then
      StepOut(st.(phase := phAwaitingPrompt(calls, done)), [cmdAskUser(c)])
    else
      var done2 := pushResult(projectCalls(calls), done, true);
      var r := (if (|done2| == |calls|) then finishBatch(st, calls, done2, false) else advance(st, calls, done2));
      StepOut(r.st, ([cmdSkipTool(c, v)] + r.cmds))
}

function recordAndContinue(st: Session, calls: seq<SCall>, done: seq<TToolResult>, isError: bool): StepOut
  requires wellFormed(st.msgs)
  requires (|calls| > 0)
  requires (|done| < |calls|)
  requires pairsTo(projectCalls(calls), done)
{
  var done2 := pushResult(projectCalls(calls), done, isError);
  if (|done2| == |calls|) then
    finishBatch(st, calls, done2, false)
  else
    advance(st, calls, done2)
}

function approvedCurrent(st: Session, calls: seq<SCall>, done: seq<TToolResult>, c: SCall): StepOut
  requires wellFormed(st.msgs)
  requires (|calls| > 0)
  requires (|done| < |calls|)
  requires pairsTo(projectCalls(calls), done)
{
  if !(c.argsOk) then
    var r := recordAndContinue(st, calls, done, true);
    StepOut(r.st, ([cmdSkipTool(c, Verdict.skipMissingArgs)] + r.cmds))
  else
    StepOut(st.(phase := phToolBatch(calls, done)), [cmdExecTool(c)])
}

function startCompact(st: Session, keep: int): StepOut
  requires wellFormed(st.msgs)
{
  if (keep < 0) then
    StepOut(st.(phase := phIdle()), [])
  else
    var cut := findCut(st.msgs, keep);
    if (cut == 0) then
      StepOut(st.(phase := phIdle()), [])
    else
      StepOut(st.(phase := phAwaitingSummary(cut)), [cmdSummarize(cut)])
}

function maybeAutoCompact(st: Session): StepOut
  requires wellFormed(st.msgs)
{
  if ((st.autoCompactAt <= 0) || (st.lastContextTokens <= st.autoCompactAt)) then
    StepOut(st.(phase := phIdle()), [])
  else
    startCompact(st, st.compactKeep)
}

function onUserInput(st: Session): StepOut
  requires inv(st)
{
  var ph := st.phase;
  match ph {
    case idle =>
      requestProvider(st.(msgs := appendUserMsg(st.msgs)))
    case _ =>
      StepOut(st, [])
  }
}

function onCompactRequest(st: Session, keep: int): StepOut
  requires inv(st)
{
  var ph := st.phase;
  match ph {
    case idle =>
      startCompact(st, keep)
    case _ =>
      StepOut(st, [])
  }
}

function onProviderReply(st: Session, calls: seq<SCall>, contextTokens: int): StepOut
  requires inv(st)
{
  var ph := st.phase;
  match ph {
    case awaitingProvider =>
      var st2 := st.(lastContextTokens := contextTokens);
      if (|calls| == 0) then
        maybeAutoCompact(st2.(msgs := appendAssistantDone(st2.msgs)))
      else
        advance(st2, calls, startResults(projectCalls(calls)))
    case _ =>
      StepOut(st, [])
  }
}

function onProviderInterrupted(st: Session): StepOut
  requires inv(st)
{
  var ph := st.phase;
  match ph {
    case awaitingProvider =>
      StepOut(st.(msgs := appendAssistantDone(st.msgs), phase := phIdle()), [])
    case _ =>
      StepOut(st, [])
  }
}

function onToolDone(st: Session, isError: bool): StepOut
  requires inv(st)
{
  var ph := st.phase;
  match ph {
    case toolBatch(i_ph_calls, i_ph_done) =>
      recordAndContinue(st, i_ph_calls, i_ph_done, isError)
    case _ =>
      StepOut(st, [])
  }
}

function onPromptAnswer(st: Session, answer: Answer): StepOut
  requires inv(st)
{
  var ph := st.phase;
  match ph {
    case awaitingPrompt(i_ph_calls, i_ph_done) =>
      var c := i_ph_calls[|i_ph_done|];
      if answer.no? then
        recordAndContinue(st, i_ph_calls, i_ph_done, true)
      else
        if answer.always? then
          approvedCurrent(st.(perms := grantFor(st.perms, st.cwd, c.req)), i_ph_calls, i_ph_done, c)
        else
          if answer.all? then
            approvedCurrent(st.(perms := grantAll(st.perms, st.cwd, c.req)), i_ph_calls, i_ph_done, c)
          else
            approvedCurrent(st, i_ph_calls, i_ph_done, c)
    case _ =>
      StepOut(st, [])
  }
}

function onBatchInterrupted(st: Session): StepOut
  requires inv(st)
{
  var ph := st.phase;
  if (ph.toolBatch? || ph.awaitingPrompt?) then
    finishBatch(st, ph.calls, fillRest(projectCalls(ph.calls), ph.done), true)
  else
    StepOut(st, [])
}

function onSummaryReady(st: Session, ok: bool): StepOut
  requires inv(st)
{
  var ph := st.phase;
  match ph {
    case awaitingSummary(i_ph_cut) =>
      if !(ok) then
        StepOut(st.(phase := phIdle()), [])
      else
        StepOut(st.(msgs := compact(st.msgs, i_ph_cut), phase := phIdle()), [])
    case _ =>
      StepOut(st, [])
  }
}

function step(st: Session, ev: SEvent): StepOut
  requires inv(st)
{
  match ev {
    case userInput =>
      onUserInput(st)
    case compactRequest(i_ev_keep) =>
      onCompactRequest(st, i_ev_keep)
    case providerReply(i_ev_calls, i_ev_contextTokens) =>
      onProviderReply(st, i_ev_calls, i_ev_contextTokens)
    case providerInterrupted =>
      onProviderInterrupted(st)
    case toolDone(i_ev_isError) =>
      onToolDone(st, i_ev_isError)
    case promptAnswer(i_ev_answer) =>
      onPromptAnswer(st, i_ev_answer)
    case batchInterrupted =>
      onBatchInterrupted(st)
    case summaryReady(i_ev_ok) =>
      onSummaryReady(st, i_ev_ok)
  }
}

function justified(st: Session, st2: Session, ev: SEvent, c: SCall): bool
{
  (c.noPerm || (isAllowed(st2.perms, st2.cwd, c.req) || (match ev { case promptAnswer(i_ev_answer) => (if (!i_ev_answer.yes?) then false else (var ph := st.phase; (match ph { case awaitingPrompt(i_ph_calls, i_ph_done) => (if (|i_ph_done| >= |i_ph_calls|) then false else (c == i_ph_calls[|i_ph_done|])) case _ => false }))) case _ => false })))
}

function stepMediation(st: Session, ev: SEvent, i: int): bool
  requires inv(st)
  requires (0 <= i)
  requires (i < |step(st, ev).cmds|)
  requires step(st, ev).cmds[i].execTool?
{
  true
}

lemma stepMediation_ensures(st: Session, ev: SEvent, i: int)
  requires inv(st)
  requires (0 <= i)
  requires (i < |step(st, ev).cmds|)
  requires step(st, ev).cmds[i].execTool?
  ensures justified(st, step(st, ev).st, ev, step(st, ev).cmds[i].call)
{
  StepOk(st, ev);
}

function stepPreservesInv(st: Session, ev: SEvent): bool
  requires inv(st)
{
  true
}

lemma stepPreservesInv_ensures(st: Session, ev: SEvent)
  requires inv(st)
  ensures inv(step(st, ev).st)
{
  StepOk(st, ev);
}

function stepProviderCallSafe(st: Session, ev: SEvent, i: int): bool
  requires inv(st)
  requires (0 <= i)
  requires (i < |step(st, ev).cmds|)
  requires step(st, ev).cmds[i].callProvider?
{
  true
}

lemma stepProviderCallSafe_ensures(st: Session, ev: SEvent, i: int)
  requires inv(st)
  requires (0 <= i)
  requires (i < |step(st, ev).cmds|)
  requires step(st, ev).cmds[i].callProvider?
  ensures step(st, ev).st.phase.awaitingProvider?
  ensures wellFormed(step(st, ev).st.msgs)
  ensures ((st.maxTurns > 0) ==> (step(st, ev).st.turns <= st.maxTurns))
{
  StepOk(st, ev);
}

function stepSummarizeSafe(st: Session, ev: SEvent, i: int): bool
  requires inv(st)
  requires (0 <= i)
  requires (i < |step(st, ev).cmds|)
  requires step(st, ev).cmds[i].summarize?
{
  true
}

lemma stepSummarizeSafe_ensures(st: Session, ev: SEvent, i: int)
  requires inv(st)
  requires (0 <= i)
  requires (i < |step(st, ev).cmds|)
  requires step(st, ev).cmds[i].summarize?
  ensures step(st, ev).st.phase.awaitingSummary?
  ensures (step(st, ev).st.phase.cut == step(st, ev).cmds[i].cut)
  ensures (0 < step(st, ev).cmds[i].cut)
  ensures (step(st, ev).cmds[i].cut <= |step(st, ev).st.msgs|)
  ensures ((step(st, ev).cmds[i].cut == |step(st, ev).st.msgs|) || headOk(step(st, ev).st.msgs[step(st, ev).cmds[i].cut]))
{
  StepOk(st, ev);
}

function stepPermsStable(st: Session, ev: SEvent): bool
  requires inv(st)
  requires (!ev.promptAnswer?)
{
  true
}

lemma stepPermsStable_ensures(st: Session, ev: SEvent)
  requires inv(st)
  requires (!ev.promptAnswer?)
  ensures (step(st, ev).st.perms == st.perms)
{
  StepOk(st, ev);
}

function stepPromptNecessary(st: Session, ev: SEvent, i: int): bool
  requires inv(st)
  requires (0 <= i)
  requires (i < |step(st, ev).cmds|)
  requires step(st, ev).cmds[i].askUser?
{
  true
}

lemma stepPromptNecessary_ensures(st: Session, ev: SEvent, i: int)
  requires inv(st)
  requires (0 <= i)
  requires (i < |step(st, ev).cmds|)
  requires step(st, ev).cmds[i].askUser?
  ensures !(step(st, ev).cmds[i].call.noPerm)
  ensures !(isAllowed(step(st, ev).st.perms, step(st, ev).st.cwd, step(st, ev).cmds[i].call.req))
{
  StepOk(st, ev);
}

function stepRejectNeverAsks(st: Session, ev: SEvent, i: int): bool
  requires inv(st)
  requires st.perms.rejectPrompts
  requires (0 <= i)
  requires (i < |step(st, ev).cmds|)
{
  true
}

lemma stepRejectNeverAsks_ensures(st: Session, ev: SEvent, i: int)
  requires inv(st)
  requires st.perms.rejectPrompts
  requires (0 <= i)
  requires (i < |step(st, ev).cmds|)
  ensures (!step(st, ev).cmds[i].askUser?)
{
  StepOk(st, ev);
}

function stepCommandDiscipline(st: Session, ev: SEvent, i: int): bool
  requires inv(st)
  requires (0 <= i)
  requires (i < (|step(st, ev).cmds| - 1))
{
  true
}

lemma stepCommandDiscipline_ensures(st: Session, ev: SEvent, i: int)
  requires inv(st)
  requires (0 <= i)
  requires (i < (|step(st, ev).cmds| - 1))
  ensures step(st, ev).cmds[i].skipTool?
{
  StepOk(st, ev);
}

function stepExecCursor(st: Session, ev: SEvent, i: int): bool
  requires inv(st)
  requires (0 <= i)
  requires (i < |step(st, ev).cmds|)
  requires step(st, ev).cmds[i].execTool?
{
  true
}

lemma stepExecCursor_ensures(st: Session, ev: SEvent, i: int)
  requires inv(st)
  requires (0 <= i)
  requires (i < |step(st, ev).cmds|)
  requires step(st, ev).cmds[i].execTool?
  ensures step(st, ev).st.phase.toolBatch?
  ensures (|step(st, ev).st.phase.done| < |step(st, ev).st.phase.calls|)
  ensures (step(st, ev).st.phase.calls[|step(st, ev).st.phase.done|] == step(st, ev).cmds[i].call)
{
  StepOk(st, ev);
}

function stepAskCursor(st: Session, ev: SEvent, i: int): bool
  requires inv(st)
  requires (0 <= i)
  requires (i < |step(st, ev).cmds|)
  requires step(st, ev).cmds[i].askUser?
{
  true
}

lemma stepAskCursor_ensures(st: Session, ev: SEvent, i: int)
  requires inv(st)
  requires (0 <= i)
  requires (i < |step(st, ev).cmds|)
  requires step(st, ev).cmds[i].askUser?
  ensures step(st, ev).st.phase.awaitingPrompt?
  ensures (|step(st, ev).st.phase.done| < |step(st, ev).st.phase.calls|)
  ensures (step(st, ev).st.phase.calls[|step(st, ev).st.phase.done|] == step(st, ev).cmds[i].call)
{
  StepOk(st, ev);
}

function batchMeasure(st: Session): int
{
  var ph := st.phase;
  match ph {
    case toolBatch(i_ph_calls, i_ph_done) =>
      (2 * (|i_ph_calls| - |i_ph_done|))
    case awaitingPrompt(i_ph_calls, i_ph_done) =>
      ((2 * (|i_ph_calls| - |i_ph_done|)) + 1)
    case _ =>
      0
  }
}

function stepBatchProgress(st: Session, ev: SEvent): bool
  requires inv(st)
  requires (st.phase.toolBatch? || st.phase.awaitingPrompt?)
  requires ((ev.toolDone? || ev.promptAnswer?) || ev.batchInterrupted?)
  requires (ev.toolDone? ==> st.phase.toolBatch?)
  requires (ev.promptAnswer? ==> st.phase.awaitingPrompt?)
{
  true
}

lemma stepBatchProgress_ensures(st: Session, ev: SEvent)
  requires inv(st)
  requires (st.phase.toolBatch? || st.phase.awaitingPrompt?)
  requires ((ev.toolDone? || ev.promptAnswer?) || ev.batchInterrupted?)
  requires (ev.toolDone? ==> st.phase.toolBatch?)
  requires (ev.promptAnswer? ==> st.phase.awaitingPrompt?)
  ensures ((step(st, ev).st.phase.toolBatch? || step(st, ev).st.phase.awaitingPrompt?) ==> (batchMeasure(step(st, ev).st) < batchMeasure(st)))
{
  StepOk(st, ev);
}

function stepConfigStable(st: Session, ev: SEvent): bool
  requires inv(st)
{
  true
}

lemma stepConfigStable_ensures(st: Session, ev: SEvent)
  requires inv(st)
  ensures (step(st, ev).st.maxTurns == st.maxTurns)
  ensures (step(st, ev).st.compactKeep == st.compactKeep)
  ensures (step(st, ev).st.autoCompactAt == st.autoCompactAt)
  ensures (st.turns <= step(st, ev).st.turns)
  ensures (step(st, ev).st.turns <= (st.turns + 1))
{
  StepOk(st, ev);
}

function stepGrantScope(st: Session, ev: SEvent): bool
  requires inv(st)
  requires ev.promptAnswer?
{
  true
}

lemma stepGrantScope_ensures(st: Session, ev: SEvent)
  requires inv(st)
  requires ev.promptAnswer?
  ensures ((step(st, ev).st.perms == st.perms) || ((st.phase.awaitingPrompt? && (|st.phase.done| < |st.phase.calls|)) && ((step(st, ev).st.perms == grantFor(st.perms, st.cwd, st.phase.calls[|st.phase.done|].req)) || (step(st, ev).st.perms == grantAll(st.perms, st.cwd, st.phase.calls[|st.phase.done|].req)))))
{
  StepOk(st, ev);
}

function stepMsgsBounded(st: Session, ev: SEvent): bool
  requires inv(st)
{
  true
}

lemma stepMsgsBounded_ensures(st: Session, ev: SEvent)
  requires inv(st)
  ensures (|step(st, ev).st.msgs| <= (|st.msgs| + 2))
  ensures (ev.summaryReady? ==> (|step(st, ev).st.msgs| <= |st.msgs|))
{
  StepOk(st, ev);
}

// ═══════════════════════════════════════════════════════════════════════════
// Proof program for the trace theorems (S1–S13).
//
// One `*Ok` lemma per transition function bundles everything that holds of its
// StepOut; `StepOk` composes them by case analysis over the event, and the
// surfaced `step*_ensures` lemmas project out of `StepOk`.
// ═══════════════════════════════════════════════════════════════════════════

// Every callProvider command is emitted into a state that awaits the provider
// with a well-formed transcript and a respected turn budget.
ghost predicate ProviderSafe(st0: Session, out: StepOut)
{
  forall k :: 0 <= k < |out.cmds| && out.cmds[k].callProvider? ==>
    out.st.phase.awaitingProvider? && wellFormed(out.st.msgs)
    && (st0.maxTurns > 0 ==> out.st.turns <= st0.maxTurns)
}

// Every summarize command's cut is the one recorded in the awaiting phase
// (its bounds and boundary safety then follow from inv(out.st)).
ghost predicate SummarizeLinked(out: StepOut)
{
  forall k :: 0 <= k < |out.cmds| && out.cmds[k].summarize? ==>
    out.st.phase.awaitingSummary? && out.st.phase.cut == out.cmds[k].cut
}

// Every execTool command's call is exempt or justified by the (unchanged)
// permission state — the helper-level half of S1; the prompt-grant cases are
// handled at the promptAnswer event.
ghost predicate ExecJustifiedBy(perms: PermState, cwd: seq<string>, out: StepOut)
{
  forall k :: 0 <= k < |out.cmds| && out.cmds[k].execTool? ==>
    out.cmds[k].call.noPerm || isAllowed(perms, cwd, out.cmds[k].call.req)
}

// S8: everything before the last command is a skipTool notification — at most
// one effectful command per step, and it is last.
ghost predicate OnlySkipsBeforeLast(out: StepOut)
{
  forall k :: 0 <= k < |out.cmds| - 1 ==> out.cmds[k].skipTool?
}

// S6: a prompt is only ever asked for a call the post-state does NOT justify.
ghost predicate PromptNecessary(out: StepOut)
{
  forall k :: 0 <= k < |out.cmds| && out.cmds[k].askUser? ==>
    !out.cmds[k].call.noPerm && !isAllowed(out.st.perms, out.st.cwd, out.cmds[k].call.req)
}

// S9: an emitted execTool / askUser call IS the post-state batch's current call.
ghost predicate CursorLinked(out: StepOut)
{
  && (forall k :: 0 <= k < |out.cmds| && out.cmds[k].execTool? ==>
      out.st.phase.toolBatch? && |out.st.phase.done| < |out.st.phase.calls|
      && out.st.phase.calls[|out.st.phase.done|] == out.cmds[k].call)
  && (forall k :: 0 <= k < |out.cmds| && out.cmds[k].askUser? ==>
      out.st.phase.awaitingPrompt? && |out.st.phase.done| < |out.st.phase.calls|
      && out.st.phase.calls[|out.st.phase.done|] == out.cmds[k].call)
}

// S7: no askUser command at all (under rejectPrompts).
ghost predicate NoAsk(out: StepOut)
{
  forall k :: 0 <= k < |out.cmds| ==> !out.cmds[k].askUser?
}

// S11: budgets and cwd are session constants; turns moves by at most one.
ghost predicate ConfigStable(st0: Session, out: StepOut)
{
  && out.st.maxTurns == st0.maxTurns
  && out.st.compactKeep == st0.compactKeep
  && out.st.autoCompactAt == st0.autoCompactAt
  && st0.turns <= out.st.turns <= st0.turns + 1
}

lemma RequestProviderOk(st: Session)
  requires wellFormed(st.msgs)
  ensures var out := requestProvider(st);
    && inv(out.st)
    && out.st.perms == st.perms && out.st.cwd == st.cwd
    && out.st.maxTurns == st.maxTurns && out.st.msgs == st.msgs
    && (out.st.phase.idle? || out.st.phase.awaitingProvider?)
    && (forall k :: 0 <= k < |out.cmds| ==> out.cmds[k].callProvider?)
    && ProviderSafe(st, out) && SummarizeLinked(out)
    && OnlySkipsBeforeLast(out) && PromptNecessary(out) && CursorLinked(out) && NoAsk(out)
    && ConfigStable(st, out)
{
}

lemma StartCompactOk(st: Session, keep: int)
  requires wellFormed(st.msgs)
  ensures var out := startCompact(st, keep);
    && inv(out.st)
    && out.st.perms == st.perms && out.st.cwd == st.cwd
    && out.st.maxTurns == st.maxTurns && out.st.msgs == st.msgs
    && out.st.turns == st.turns
    && (out.st.phase.idle? || out.st.phase.awaitingSummary?)
    && (forall k :: 0 <= k < |out.cmds| ==> out.cmds[k].summarize?)
    && ProviderSafe(st, out) && SummarizeLinked(out)
    && OnlySkipsBeforeLast(out) && PromptNecessary(out) && CursorLinked(out) && NoAsk(out)
    && ConfigStable(st, out)
{
}

lemma MaybeAutoCompactOk(st: Session)
  requires wellFormed(st.msgs)
  ensures var out := maybeAutoCompact(st);
    && inv(out.st)
    && out.st.perms == st.perms && out.st.cwd == st.cwd
    && out.st.maxTurns == st.maxTurns && out.st.msgs == st.msgs
    && (out.st.phase.idle? || out.st.phase.awaitingSummary?)
    && (forall k :: 0 <= k < |out.cmds| ==> out.cmds[k].summarize?)
    && ProviderSafe(st, out) && SummarizeLinked(out)
    && OnlySkipsBeforeLast(out) && PromptNecessary(out) && CursorLinked(out) && NoAsk(out)
    && ConfigStable(st, out)
{
  if !(st.autoCompactAt <= 0 || st.lastContextTokens <= st.autoCompactAt) {
    StartCompactOk(st, st.compactKeep);
  }
}

lemma FinishBatchOk(st: Session, calls: seq<SCall>, done: seq<TToolResult>, stopped: bool)
  requires wellFormed(st.msgs)
  requires |calls| > 0
  requires pairs(projectCalls(calls), done)
  ensures var out := finishBatch(st, calls, done, stopped);
    && inv(out.st)
    && out.st.perms == st.perms && out.st.cwd == st.cwd && out.st.maxTurns == st.maxTurns
    && !out.st.phase.toolBatch? && !out.st.phase.awaitingPrompt?
    && |out.st.msgs| == |st.msgs| + 2
    && (forall k :: 0 <= k < |out.cmds| ==> out.cmds[k].callProvider?)
    && ProviderSafe(st, out) && SummarizeLinked(out)
    && OnlySkipsBeforeLast(out) && PromptNecessary(out) && CursorLinked(out) && NoAsk(out)
    && ConfigStable(st, out)
{
  var msgs2 := appendAnsweredBlock(st.msgs, projectCalls(calls), done);
  if !stopped {
    RequestProviderOk(st.(msgs := msgs2));
  }
}

lemma AdvanceOk(st: Session, calls: seq<SCall>, done: seq<TToolResult>)
  requires wellFormed(st.msgs)
  requires |calls| > 0
  requires |done| < |calls|
  requires pairsTo(projectCalls(calls), done)
  decreases |calls| - |done|
  ensures var out := advance(st, calls, done);
    && inv(out.st)
    && out.st.perms == st.perms && out.st.cwd == st.cwd && out.st.maxTurns == st.maxTurns
    && ExecJustifiedBy(st.perms, st.cwd, out)
    && ProviderSafe(st, out) && SummarizeLinked(out)
    && OnlySkipsBeforeLast(out) && PromptNecessary(out) && CursorLinked(out)
    && (st.perms.rejectPrompts ==> NoAsk(out))
    && ConfigStable(st, out)
    && |out.st.msgs| <= |st.msgs| + 2
    && ((out.st.phase.toolBatch? || out.st.phase.awaitingPrompt?) ==> batchMeasure(out.st) <= 2 * (|calls| - |done|) + 1)
{
  var c := calls[|done|];
  var v := verdictFor(st, c);
  verdictFor_ensures(st, c);
  if v.exec? {
  } else if v.prompt? {
  } else {
    var done2 := pushResult(projectCalls(calls), done, true);
    var r := (if |done2| == |calls| then finishBatch(st, calls, done2, false) else advance(st, calls, done2));
    if |done2| == |calls| {
      FinishBatchOk(st, calls, done2, false);
    } else {
      AdvanceOk(st, calls, done2);
    }
    assert advance(st, calls, done).cmds == [cmdSkipTool(c, v)] + r.cmds;
    assert forall k :: 1 <= k < |advance(st, calls, done).cmds| ==> advance(st, calls, done).cmds[k] == r.cmds[k - 1];
  }
}

lemma RecordAndContinueOk(st: Session, calls: seq<SCall>, done: seq<TToolResult>, isError: bool)
  requires wellFormed(st.msgs)
  requires |calls| > 0
  requires |done| < |calls|
  requires pairsTo(projectCalls(calls), done)
  ensures var out := recordAndContinue(st, calls, done, isError);
    && inv(out.st)
    && out.st.perms == st.perms && out.st.cwd == st.cwd && out.st.maxTurns == st.maxTurns
    && ExecJustifiedBy(st.perms, st.cwd, out)
    && ProviderSafe(st, out) && SummarizeLinked(out)
    && OnlySkipsBeforeLast(out) && PromptNecessary(out) && CursorLinked(out)
    && (st.perms.rejectPrompts ==> NoAsk(out))
    && ConfigStable(st, out)
    && |out.st.msgs| <= |st.msgs| + 2
    && ((out.st.phase.toolBatch? || out.st.phase.awaitingPrompt?) ==> batchMeasure(out.st) <= 2 * (|calls| - |done|) - 1)
{
  var done2 := pushResult(projectCalls(calls), done, isError);
  if |done2| == |calls| {
    FinishBatchOk(st, calls, done2, false);
  } else {
    AdvanceOk(st, calls, done2);
  }
}

// approvedCurrent's own execTool is exactly `c` (the prompted call, which the
// caller passes as the batch cursor); every other command it can emit is
// covered by the unchanged-perms justification.
lemma ApprovedCurrentOk(st: Session, calls: seq<SCall>, done: seq<TToolResult>, c: SCall)
  requires wellFormed(st.msgs)
  requires |calls| > 0
  requires |done| < |calls|
  requires pairsTo(projectCalls(calls), done)
  requires c == calls[|done|]
  ensures var out := approvedCurrent(st, calls, done, c);
    && inv(out.st)
    && out.st.perms == st.perms && out.st.cwd == st.cwd && out.st.maxTurns == st.maxTurns
    && (forall k :: 0 <= k < |out.cmds| && out.cmds[k].execTool? ==>
        out.cmds[k].call == c || out.cmds[k].call.noPerm || isAllowed(st.perms, st.cwd, out.cmds[k].call.req))
    && ProviderSafe(st, out) && SummarizeLinked(out)
    && OnlySkipsBeforeLast(out) && PromptNecessary(out) && CursorLinked(out)
    && (st.perms.rejectPrompts ==> NoAsk(out))
    && ConfigStable(st, out)
    && |out.st.msgs| <= |st.msgs| + 2
    && ((out.st.phase.toolBatch? || out.st.phase.awaitingPrompt?) ==> batchMeasure(out.st) <= 2 * (|calls| - |done|))
{
  if !c.argsOk {
    var r := recordAndContinue(st, calls, done, true);
    RecordAndContinueOk(st, calls, done, true);
    assert approvedCurrent(st, calls, done, c).cmds == [cmdSkipTool(c, Verdict.skipMissingArgs)] + r.cmds;
    assert forall k :: 1 <= k < |approvedCurrent(st, calls, done, c).cmds| ==> approvedCurrent(st, calls, done, c).cmds[k] == r.cmds[k - 1];
  }
}

// The master lemma: everything the surfaced theorems project out of one step.
lemma StepOk(st: Session, ev: SEvent)
  requires inv(st)
  ensures var out := step(st, ev);
    && inv(out.st)
    && out.st.cwd == st.cwd && out.st.maxTurns == st.maxTurns
    && (!ev.promptAnswer? ==> out.st.perms == st.perms)
    && (forall k :: 0 <= k < |out.cmds| && out.cmds[k].execTool? ==> justified(st, out.st, ev, out.cmds[k].call))
    && ProviderSafe(st, out) && SummarizeLinked(out)
    && OnlySkipsBeforeLast(out) && PromptNecessary(out) && CursorLinked(out)
    && (st.perms.rejectPrompts ==> NoAsk(out))
    && ConfigStable(st, out)
    && |out.st.msgs| <= |st.msgs| + 2
    && (ev.summaryReady? ==> |out.st.msgs| <= |st.msgs|)
    && (((st.phase.toolBatch? || st.phase.awaitingPrompt?)
         && (ev.toolDone? || ev.promptAnswer? || ev.batchInterrupted?)
         && (ev.toolDone? ==> st.phase.toolBatch?)
         && (ev.promptAnswer? ==> st.phase.awaitingPrompt?))
        ==> ((out.st.phase.toolBatch? || out.st.phase.awaitingPrompt?) ==> batchMeasure(out.st) < batchMeasure(st)))
    && (ev.promptAnswer? ==>
        (out.st.perms == st.perms
         || (st.phase.awaitingPrompt? && |st.phase.done| < |st.phase.calls|
             && (out.st.perms == grantFor(st.perms, st.cwd, st.phase.calls[|st.phase.done|].req)
                 || out.st.perms == grantAll(st.perms, st.cwd, st.phase.calls[|st.phase.done|].req)))))
{
  match ev {
    case userInput =>
      if st.phase.idle? {
        RequestProviderOk(st.(msgs := appendUserMsg(st.msgs)));
      }
    case compactRequest(keep) =>
      if st.phase.idle? {
        StartCompactOk(st, keep);
      }
    case providerReply(calls, contextTokens) =>
      if st.phase.awaitingProvider? {
        var st2 := st.(lastContextTokens := contextTokens);
        if |calls| == 0 {
          MaybeAutoCompactOk(st2.(msgs := appendAssistantDone(st2.msgs)));
        } else {
          AdvanceOk(st2, calls, startResults(projectCalls(calls)));
        }
      }
    case providerInterrupted =>
    case toolDone(isError) =>
      if st.phase.toolBatch? {
        RecordAndContinueOk(st, st.phase.calls, st.phase.done, isError);
      }
    case promptAnswer(answer) =>
      if st.phase.awaitingPrompt? {
        var c := st.phase.calls[|st.phase.done|];
        if answer.no? {
          RecordAndContinueOk(st, st.phase.calls, st.phase.done, true);
        } else if answer.always? {
          ApprovedCurrentOk(st.(perms := grantFor(st.perms, st.cwd, c.req)), st.phase.calls, st.phase.done, c);
        } else if answer.all? {
          ApprovedCurrentOk(st.(perms := grantAll(st.perms, st.cwd, c.req)), st.phase.calls, st.phase.done, c);
        } else {
          ApprovedCurrentOk(st, st.phase.calls, st.phase.done, c);
        }
      }
    case batchInterrupted =>
      if st.phase.toolBatch? || st.phase.awaitingPrompt? {
        FinishBatchOk(st, st.phase.calls, fillRest(projectCalls(st.phase.calls), st.phase.done), true);
      }
    case summaryReady(ok) =>
  }
}
