// Generated by lsc from transcript.ts

datatype TToolCall = TToolCall(id: string, name: string)

datatype TToolResult = TToolResult(toolCallId: string, isError: bool)

datatype TMsg = user | assistant(toolCalls: seq<TToolCall>) | tool(toolResults: seq<TToolResult>)

function pairs(calls: seq<TToolCall>, results: seq<TToolResult>): bool
  decreases |calls|
{
  if (|results| != |calls|) then
    false
  else
    ((|calls| == 0) || (if (results[0].toolCallId != calls[0].id) then false else pairs(calls[1..], results[1..])))
}

function makeResults(calls: seq<TToolCall>): seq<TToolResult>
  decreases |calls|
{
  if (|calls| == 0) then
    []
  else
    ([TToolResult(calls[0].id, false)] + makeResults(calls[1..]))
}

lemma makeResults_ensures(calls: seq<TToolCall>)
  ensures (|makeResults(calls)| == |calls|)
  ensures pairs(calls, makeResults(calls))
{
}

function headOk(m: TMsg): bool
{
  (!m.tool?)
}

function lastOk(m: TMsg): bool
{
  match m {
    case assistant(i_m_toolCalls) =>
      (|i_m_toolCalls| == 0)
    case _ =>
      true
  }
}

function okAdjacent(a: TMsg, b: TMsg): bool
{
  match a {
    case assistant(i_a_toolCalls) =>
      if (|i_a_toolCalls| > 0) then
        match b {
          case tool(i_b_toolResults) =>
            pairs(i_a_toolCalls, i_b_toolResults)
          case _ =>
            false
        }
      else
        (!b.tool?)
    case _ =>
      (!b.tool?)
  }
}

function wfFrom(msgs: seq<TMsg>): bool
  decreases |msgs|
{
  ((|msgs| == 0) || (if (|msgs| == 1) then lastOk(msgs[0]) else (okAdjacent(msgs[0], msgs[1]) && wfFrom(msgs[1..]))))
}

function wellFormed(msgs: seq<TMsg>): bool
{
  ((|msgs| == 0) || (headOk(msgs[0]) && wfFrom(msgs)))
}

function snapBack(msgs: seq<TMsg>, c: int): int
  requires (0 <= c)
  requires (c <= |msgs|)
  decreases c
{
  if (c >= |msgs|) then
    |msgs|
  else
    if headOk(msgs[c]) then
      c
    else
      if (c == 0) then
        |msgs|
      else
        snapBack(msgs, (c - 1))
}

lemma snapBack_ensures(msgs: seq<TMsg>, c: int)
  requires (0 <= c)
  requires (c <= |msgs|)
  ensures (0 <= snapBack(msgs, c))
  ensures (snapBack(msgs, c) <= |msgs|)
  ensures ((snapBack(msgs, c) == |msgs|) || headOk(msgs[snapBack(msgs, c)]))
{
  if (c >= |msgs|) {
  } else if (headOk(msgs[c])) {
  } else if (c == 0) {
  } else {
    snapBack_ensures(msgs, (c - 1));
  }
}

function findCut(msgs: seq<TMsg>, keepRecent: int): int
  requires (0 <= keepRecent)
{
  var want := (if (|msgs| > keepRecent) then (|msgs| - keepRecent) else 0);
  snapBack(msgs, want)
}

lemma findCut_ensures(msgs: seq<TMsg>, keepRecent: int)
  requires (0 <= keepRecent)
  ensures (0 <= findCut(msgs, keepRecent))
  ensures (findCut(msgs, keepRecent) <= |msgs|)
  ensures ((findCut(msgs, keepRecent) == |msgs|) || headOk(msgs[findCut(msgs, keepRecent)]))
{
  var want := (if (|msgs| > keepRecent) then (|msgs| - keepRecent) else 0);
  snapBack_ensures(msgs, want);
  assert findCut(msgs, keepRecent) == snapBack(msgs, want);
}

// ═══════════════════════════════════════════════════════════════════════════
// Builders + surfaced properties (generated from transcript.ts).
// The builder bodies hold the list concatenation //@ specs cannot express; the
// `_ensures` lemma bodies below are the proofs (T2 / C1 / C2 / C3 + helpers).
// ═══════════════════════════════════════════════════════════════════════════

function appendPair(msgs: seq<TMsg>, a: TMsg, t: TMsg): seq<TMsg>
{
  (msgs + [a, t])
}

function appendToolBlock(msgs: seq<TMsg>, calls: seq<TToolCall>): seq<TMsg>
{
  appendPair(msgs, assistant(calls), tool(makeResults(calls)))
}

function compact(msgs: seq<TMsg>, c: int): seq<TMsg>
  requires (0 <= c)
  requires (c <= |msgs|)
{
  ([TMsg.user] + msgs[c..])
}

function wfFromImpliesLastOk(msgs: seq<TMsg>): bool
  requires (|msgs| > 0)
  requires wfFrom(msgs)
  decreases |msgs|
{
  true
}

lemma wfFromImpliesLastOk_ensures(msgs: seq<TMsg>)
  requires (|msgs| > 0)
  requires wfFrom(msgs)
  ensures lastOk(msgs[(|msgs| - 1)])
  decreases |msgs|
{
  if |msgs| == 1 {
  } else {
    wfFromImpliesLastOk_ensures(msgs[1..]);
    assert msgs[1..][|msgs[1..]| - 1] == msgs[|msgs| - 1];
  }
}

function wfFromSuffix(msgs: seq<TMsg>, c: int): bool
  requires (0 <= c)
  requires (c <= |msgs|)
  requires wfFrom(msgs)
  decreases c
{
  true
}

lemma wfFromSuffix_ensures(msgs: seq<TMsg>, c: int)
  requires (0 <= c)
  requires (c <= |msgs|)
  requires wfFrom(msgs)
  ensures wfFrom(msgs[c..])
  decreases c
{
  if c == 0 {
    assert msgs[0..] == msgs;
  } else {
    assert wfFrom(msgs[1..]);
    wfFromSuffix_ensures(msgs[1..], c - 1);
    assert msgs[1..][(c - 1)..] == msgs[c..];
  }
}

function wfFromAppendPair(msgs: seq<TMsg>, a: TMsg, t: TMsg): bool
  requires (|msgs| > 0)
  requires wfFrom(msgs)
  requires okAdjacent(msgs[(|msgs| - 1)], a)
  requires okAdjacent(a, t)
  requires lastOk(t)
  decreases |msgs|
{
  true
}

lemma wfFromAppendPair_ensures(msgs: seq<TMsg>, a: TMsg, t: TMsg)
  requires (|msgs| > 0)
  requires wfFrom(msgs)
  requires okAdjacent(msgs[(|msgs| - 1)], a)
  requires okAdjacent(a, t)
  requires lastOk(t)
  ensures wfFrom(appendPair(msgs, a, t))
  decreases |msgs|
{
  assert appendPair(msgs, a, t) == msgs + [a, t];
  if |msgs| == 1 {
    assert (msgs + [a, t])[1..] == [a, t];
  } else {
    assert msgs[1..][|msgs[1..]| - 1] == msgs[|msgs| - 1];
    wfFromAppendPair_ensures(msgs[1..], a, t);
    assert appendPair(msgs[1..], a, t) == msgs[1..] + [a, t];
    assert (msgs + [a, t])[1..] == msgs[1..] + [a, t];
  }
}

function appendPreservesWellFormed(msgs: seq<TMsg>, calls: seq<TToolCall>): bool
  requires wellFormed(msgs)
  requires (|calls| > 0)
{
  true
}

lemma appendPreservesWellFormed_ensures(msgs: seq<TMsg>, calls: seq<TToolCall>)
  requires wellFormed(msgs)
  requires (|calls| > 0)
  ensures wellFormed(appendToolBlock(msgs, calls))
{
  var a := assistant(calls);
  var t := tool(makeResults(calls));
  makeResults_ensures(calls);
  assert appendToolBlock(msgs, calls) == appendPair(msgs, a, t);
  assert appendPair(msgs, a, t) == msgs + [a, t];
  assert okAdjacent(a, t);
  assert lastOk(t);
  if |msgs| == 0 {
    assert msgs + [a, t] == [a, t];
    assert (msgs + [a, t])[1..] == [t];
  } else {
    wfFromImpliesLastOk_ensures(msgs);
    assert okAdjacent(msgs[|msgs| - 1], a);
    wfFromAppendPair_ensures(msgs, a, t);
    assert (msgs + [a, t])[0] == msgs[0];
  }
}

function compactPreservesWellFormed(msgs: seq<TMsg>, c: int): bool
  requires wellFormed(msgs)
  requires (0 <= c)
  requires (c <= |msgs|)
  requires ((c == |msgs|) || headOk(msgs[c]))
{
  true
}

lemma compactPreservesWellFormed_ensures(msgs: seq<TMsg>, c: int)
  requires wellFormed(msgs)
  requires (0 <= c)
  requires (c <= |msgs|)
  requires ((c == |msgs|) || headOk(msgs[c]))
  ensures wellFormed(compact(msgs, c))
{
  assert wfFrom(msgs);
  wfFromSuffix_ensures(msgs, c);
  assert compact(msgs, c) == [TMsg.user] + msgs[c..];
  var suffix := msgs[c..];
  var res := [TMsg.user] + suffix;
  if |suffix| == 0 {
    assert res == [TMsg.user];
  } else {
    assert c < |msgs|;
    assert headOk(msgs[c]);
    assert res[1..] == suffix;
    assert suffix[0] == msgs[c];
    assert okAdjacent(TMsg.user, suffix[0]);
  }
}

function compactNonGrowing(msgs: seq<TMsg>, c: int): bool
  requires (1 <= c)
  requires (c <= |msgs|)
{
  true
}

lemma compactNonGrowing_ensures(msgs: seq<TMsg>, c: int)
  requires (1 <= c)
  requires (c <= |msgs|)
  ensures (|compact(msgs, c)| <= |msgs|)
{
  assert compact(msgs, c) == [TMsg.user] + msgs[c..];
  assert |[TMsg.user] + msgs[c..]| == 1 + (|msgs| - c);
}

function compactShrinks(msgs: seq<TMsg>, c: int): bool
  requires (2 <= c)
  requires (c <= |msgs|)
{
  true
}

lemma compactShrinks_ensures(msgs: seq<TMsg>, c: int)
  requires (2 <= c)
  requires (c <= |msgs|)
  ensures (|compact(msgs, c)| < |msgs|)
{
  assert compact(msgs, c) == [TMsg.user] + msgs[c..];
  assert |[TMsg.user] + msgs[c..]| == 1 + (|msgs| - c);
}

function compactConverges(msgs: seq<TMsg>, keepRecent: int): bool
  requires (0 <= keepRecent)
  requires wellFormed(msgs)
  requires (|msgs| <= keepRecent)
{
  true
}

lemma compactConverges_ensures(msgs: seq<TMsg>, keepRecent: int)
  requires (0 <= keepRecent)
  requires wellFormed(msgs)
  requires (|msgs| <= keepRecent)
  ensures (findCut(msgs, keepRecent) == 0)
{
  if |msgs| > 0 {
    assert headOk(msgs[0]);
  }
}
