// Generated by lsc from transcript.ts

datatype TToolCall = TToolCall(id: string, name: string)

datatype TToolResult = TToolResult(toolCallId: string, isError: bool)

datatype TMsg = user | assistant(toolCalls: seq<TToolCall>) | tool(toolResults: seq<TToolResult>)

function pairs(calls: seq<TToolCall>, results: seq<TToolResult>): bool
  decreases |calls|
{
  if (|results| != |calls|) then
    false
  else
    ((|calls| == 0) || (if (results[0].toolCallId != calls[0].id) then false else pairs(calls[1..], results[1..])))
}

function makeResults(calls: seq<TToolCall>): seq<TToolResult>
  decreases |calls|
{
  if (|calls| == 0) then
    []
  else
    ([TToolResult(calls[0].id, false)] + makeResults(calls[1..]))
}

lemma makeResults_ensures(calls: seq<TToolCall>)
  ensures (|makeResults(calls)| == |calls|)
  ensures pairs(calls, makeResults(calls))
{
}

function headOk(m: TMsg): bool
{
  (!m.tool?)
}

function lastOk(m: TMsg): bool
{
  match m {
    case assistant(i_m_toolCalls) =>
      (|i_m_toolCalls| == 0)
    case _ =>
      true
  }
}

function okAdjacent(a: TMsg, b: TMsg): bool
{
  match a {
    case assistant(i_a_toolCalls) =>
      if (|i_a_toolCalls| > 0) then
        match b {
          case tool(i_b_toolResults) =>
            pairs(i_a_toolCalls, i_b_toolResults)
          case _ =>
            false
        }
      else
        (!b.tool?)
    case _ =>
      (!b.tool?)
  }
}

function wfFrom(msgs: seq<TMsg>): bool
  decreases |msgs|
{
  ((|msgs| == 0) || (if (|msgs| == 1) then lastOk(msgs[0]) else (okAdjacent(msgs[0], msgs[1]) && wfFrom(msgs[1..]))))
}

function wellFormed(msgs: seq<TMsg>): bool
{
  ((|msgs| == 0) || (headOk(msgs[0]) && wfFrom(msgs)))
}

function snapBack(msgs: seq<TMsg>, c: int): int
  requires (0 <= c)
  requires (c <= |msgs|)
  decreases c
{
  if (c >= |msgs|) then
    |msgs|
  else
    if headOk(msgs[c]) then
      c
    else
      if (c == 0) then
        |msgs|
      else
        snapBack(msgs, (c - 1))
}

lemma snapBack_ensures(msgs: seq<TMsg>, c: int)
  requires (0 <= c)
  requires (c <= |msgs|)
  ensures (0 <= snapBack(msgs, c))
  ensures (snapBack(msgs, c) <= |msgs|)
  ensures ((snapBack(msgs, c) == |msgs|) || headOk(msgs[snapBack(msgs, c)]))
{
  if (c >= |msgs|) {
  } else if (headOk(msgs[c])) {
  } else if (c == 0) {
  } else {
    snapBack_ensures(msgs, (c - 1));
  }
}

function findCut(msgs: seq<TMsg>, keepRecent: int): int
  requires (0 <= keepRecent)
{
  var want := (if (|msgs| > keepRecent) then (|msgs| - keepRecent) else 0);
  snapBack(msgs, want)
}

lemma findCut_ensures(msgs: seq<TMsg>, keepRecent: int)
  requires (0 <= keepRecent)
  ensures (0 <= findCut(msgs, keepRecent))
  ensures (findCut(msgs, keepRecent) <= |msgs|)
  ensures ((findCut(msgs, keepRecent) == |msgs|) || headOk(msgs[findCut(msgs, keepRecent)]))
{
  var want := (if (|msgs| > keepRecent) then (|msgs| - keepRecent) else 0);
  snapBack_ensures(msgs, want);
  assert findCut(msgs, keepRecent) == snapBack(msgs, want);
}

// ═══════════════════════════════════════════════════════════════════════════
// Builders + surfaced properties (generated from transcript.ts).
// The builder bodies hold the list concatenation //@ specs cannot express; the
// `_ensures` lemma bodies below are the proofs (T2 / C1 / C2 / C3 + helpers).
// ═══════════════════════════════════════════════════════════════════════════

function appendPair(msgs: seq<TMsg>, a: TMsg, t: TMsg): seq<TMsg>
{
  (msgs + [a, t])
}

function appendToolBlock(msgs: seq<TMsg>, calls: seq<TToolCall>): seq<TMsg>
{
  appendPair(msgs, assistant(calls), tool(makeResults(calls)))
}

function compact(msgs: seq<TMsg>, c: int): seq<TMsg>
  requires (0 <= c)
  requires (c <= |msgs|)
{
  ([TMsg.user] + msgs[c..])
}

lemma compact_ensures(msgs: seq<TMsg>, c: int)
  requires (0 <= c)
  requires (c <= |msgs|)
  ensures (wellFormed(msgs) ==> ((c == |msgs|) || headOk(msgs[c])) ==> wellFormed(compact(msgs, c)))
{
  if wellFormed(msgs) && ((c == |msgs|) || headOk(msgs[c])) {
    compactPreservesWellFormed_ensures(msgs, c);
  }
}

function wfFromImpliesLastOk(msgs: seq<TMsg>): bool
  requires (|msgs| > 0)
  requires wfFrom(msgs)
  decreases |msgs|
{
  true
}

lemma wfFromImpliesLastOk_ensures(msgs: seq<TMsg>)
  requires (|msgs| > 0)
  requires wfFrom(msgs)
  ensures lastOk(msgs[(|msgs| - 1)])
  decreases |msgs|
{
  if |msgs| == 1 {
  } else {
    wfFromImpliesLastOk_ensures(msgs[1..]);
    assert msgs[1..][|msgs[1..]| - 1] == msgs[|msgs| - 1];
  }
}

function wfFromSuffix(msgs: seq<TMsg>, c: int): bool
  requires (0 <= c)
  requires (c <= |msgs|)
  requires wfFrom(msgs)
  decreases c
{
  true
}

lemma wfFromSuffix_ensures(msgs: seq<TMsg>, c: int)
  requires (0 <= c)
  requires (c <= |msgs|)
  requires wfFrom(msgs)
  ensures wfFrom(msgs[c..])
  decreases c
{
  if c == 0 {
    assert msgs[0..] == msgs;
  } else {
    assert wfFrom(msgs[1..]);
    wfFromSuffix_ensures(msgs[1..], c - 1);
    assert msgs[1..][(c - 1)..] == msgs[c..];
  }
}

function wfFromAppendPair(msgs: seq<TMsg>, a: TMsg, t: TMsg): bool
  requires (|msgs| > 0)
  requires wfFrom(msgs)
  requires okAdjacent(msgs[(|msgs| - 1)], a)
  requires okAdjacent(a, t)
  requires lastOk(t)
  decreases |msgs|
{
  true
}

lemma wfFromAppendPair_ensures(msgs: seq<TMsg>, a: TMsg, t: TMsg)
  requires (|msgs| > 0)
  requires wfFrom(msgs)
  requires okAdjacent(msgs[(|msgs| - 1)], a)
  requires okAdjacent(a, t)
  requires lastOk(t)
  ensures wfFrom(appendPair(msgs, a, t))
  decreases |msgs|
{
  assert appendPair(msgs, a, t) == msgs + [a, t];
  if |msgs| == 1 {
    assert (msgs + [a, t])[1..] == [a, t];
  } else {
    assert msgs[1..][|msgs[1..]| - 1] == msgs[|msgs| - 1];
    wfFromAppendPair_ensures(msgs[1..], a, t);
    assert appendPair(msgs[1..], a, t) == msgs[1..] + [a, t];
    assert (msgs + [a, t])[1..] == msgs[1..] + [a, t];
  }
}

function appendPreservesWellFormed(msgs: seq<TMsg>, calls: seq<TToolCall>): bool
  requires wellFormed(msgs)
  requires (|calls| > 0)
{
  true
}

lemma appendPreservesWellFormed_ensures(msgs: seq<TMsg>, calls: seq<TToolCall>)
  requires wellFormed(msgs)
  requires (|calls| > 0)
  ensures wellFormed(appendToolBlock(msgs, calls))
{
  var a := assistant(calls);
  var t := tool(makeResults(calls));
  makeResults_ensures(calls);
  assert appendToolBlock(msgs, calls) == appendPair(msgs, a, t);
  assert appendPair(msgs, a, t) == msgs + [a, t];
  assert okAdjacent(a, t);
  assert lastOk(t);
  if |msgs| == 0 {
    assert msgs + [a, t] == [a, t];
    assert (msgs + [a, t])[1..] == [t];
  } else {
    wfFromImpliesLastOk_ensures(msgs);
    assert okAdjacent(msgs[|msgs| - 1], a);
    wfFromAppendPair_ensures(msgs, a, t);
    assert (msgs + [a, t])[0] == msgs[0];
  }
}

function compactPreservesWellFormed(msgs: seq<TMsg>, c: int): bool
  requires wellFormed(msgs)
  requires (0 <= c)
  requires (c <= |msgs|)
  requires ((c == |msgs|) || headOk(msgs[c]))
{
  true
}

lemma compactPreservesWellFormed_ensures(msgs: seq<TMsg>, c: int)
  requires wellFormed(msgs)
  requires (0 <= c)
  requires (c <= |msgs|)
  requires ((c == |msgs|) || headOk(msgs[c]))
  ensures wellFormed(compact(msgs, c))
{
  assert wfFrom(msgs);
  wfFromSuffix_ensures(msgs, c);
  assert compact(msgs, c) == [TMsg.user] + msgs[c..];
  var suffix := msgs[c..];
  var res := [TMsg.user] + suffix;
  if |suffix| == 0 {
    assert res == [TMsg.user];
  } else {
    assert c < |msgs|;
    assert headOk(msgs[c]);
    assert res[1..] == suffix;
    assert suffix[0] == msgs[c];
    assert okAdjacent(TMsg.user, suffix[0]);
  }
}

function compactNonGrowing(msgs: seq<TMsg>, c: int): bool
  requires (1 <= c)
  requires (c <= |msgs|)
{
  true
}

lemma compactNonGrowing_ensures(msgs: seq<TMsg>, c: int)
  requires (1 <= c)
  requires (c <= |msgs|)
  ensures (|compact(msgs, c)| <= |msgs|)
{
  assert compact(msgs, c) == [TMsg.user] + msgs[c..];
  assert |[TMsg.user] + msgs[c..]| == 1 + (|msgs| - c);
}

function compactShrinks(msgs: seq<TMsg>, c: int): bool
  requires (2 <= c)
  requires (c <= |msgs|)
{
  true
}

lemma compactShrinks_ensures(msgs: seq<TMsg>, c: int)
  requires (2 <= c)
  requires (c <= |msgs|)
  ensures (|compact(msgs, c)| < |msgs|)
{
  assert compact(msgs, c) == [TMsg.user] + msgs[c..];
  assert |[TMsg.user] + msgs[c..]| == 1 + (|msgs| - c);
}

function compactConverges(msgs: seq<TMsg>, keepRecent: int): bool
  requires (0 <= keepRecent)
  requires wellFormed(msgs)
  requires (|msgs| <= keepRecent)
{
  true
}

lemma compactConverges_ensures(msgs: seq<TMsg>, keepRecent: int)
  requires (0 <= keepRecent)
  requires wellFormed(msgs)
  requires (|msgs| <= keepRecent)
  ensures (findCut(msgs, keepRecent) == 0)
{
  if |msgs| > 0 {
    assert headOk(msgs[0]);
  }
}

function initialMsgs(): seq<TMsg>
{
  []
}

lemma initialMsgs_ensures()
  ensures wellFormed(initialMsgs())
  ensures (|initialMsgs()| == 0)
{
}

function appendUserMsg(msgs: seq<TMsg>): seq<TMsg>
  requires wellFormed(msgs)
{
  (msgs + [TMsg.user])
}

lemma appendUserMsg_ensures(msgs: seq<TMsg>)
  requires wellFormed(msgs)
  ensures wellFormed(appendUserMsg(msgs))
  ensures (|appendUserMsg(msgs)| == (|msgs| + 1))
{
  if |msgs| == 0 {
    assert msgs + [TMsg.user] == [TMsg.user];
  } else {
    wfFromImpliesLastOk_ensures(msgs);
    assert okAdjacent(msgs[|msgs| - 1], TMsg.user);
    WfFromAppendOne(msgs, TMsg.user);
    assert (msgs + [TMsg.user])[0] == msgs[0];
  }
}

function appendAssistantDone(msgs: seq<TMsg>): seq<TMsg>
  requires wellFormed(msgs)
{
  (msgs + [assistant([])])
}

lemma appendAssistantDone_ensures(msgs: seq<TMsg>)
  requires wellFormed(msgs)
  ensures wellFormed(appendAssistantDone(msgs))
  ensures (|appendAssistantDone(msgs)| == (|msgs| + 1))
{
  if |msgs| == 0 {
    assert msgs + [assistant([])] == [assistant([])];
  } else {
    wfFromImpliesLastOk_ensures(msgs);
    assert okAdjacent(msgs[|msgs| - 1], assistant([]));
    WfFromAppendOne(msgs, assistant([]));
    assert (msgs + [assistant([])])[0] == msgs[0];
  }
}

function appendAnsweredBlock(msgs: seq<TMsg>, calls: seq<TToolCall>, results: seq<TToolResult>): seq<TMsg>
  requires wellFormed(msgs)
  requires (|calls| > 0)
  requires pairs(calls, results)
{
  appendPair(msgs, assistant(calls), tool(results))
}

lemma appendAnsweredBlock_ensures(msgs: seq<TMsg>, calls: seq<TToolCall>, results: seq<TToolResult>)
  requires wellFormed(msgs)
  requires (|calls| > 0)
  requires pairs(calls, results)
  ensures wellFormed(appendAnsweredBlock(msgs, calls, results))
{
  var a := assistant(calls);
  var t := tool(results);
  assert okAdjacent(a, t);
  assert lastOk(t);
  assert appendAnsweredBlock(msgs, calls, results) == appendPair(msgs, a, t);
  assert appendPair(msgs, a, t) == msgs + [a, t];
  if |msgs| == 0 {
    assert msgs + [a, t] == [a, t];
    assert (msgs + [a, t])[1..] == [t];
  } else {
    wfFromImpliesLastOk_ensures(msgs);
    assert okAdjacent(msgs[|msgs| - 1], a);
    wfFromAppendPair_ensures(msgs, a, t);
    assert (msgs + [a, t])[0] == msgs[0];
  }
}

function pairsTo(calls: seq<TToolCall>, results: seq<TToolResult>): bool
  decreases |calls|
{
  if (|results| > |calls|) then
    false
  else
    ((|results| == 0) || (if (|calls| == 0) then false else (if (results[0].toolCallId != calls[0].id) then false else pairsTo(calls[1..], results[1..]))))
}

function startResults(calls: seq<TToolCall>): seq<TToolResult>
{
  []
}

lemma startResults_ensures(calls: seq<TToolCall>)
  ensures pairsTo(calls, startResults(calls))
  ensures (|startResults(calls)| == 0)
{
}

function pushResult(calls: seq<TToolCall>, done: seq<TToolResult>, isError: bool): seq<TToolResult>
  requires pairsTo(calls, done)
  requires (|done| < |calls|)
{
  (done + [TToolResult(calls[|done|].id, isError)])
}

lemma pushResult_ensures(calls: seq<TToolCall>, done: seq<TToolResult>, isError: bool)
  requires pairsTo(calls, done)
  requires (|done| < |calls|)
  ensures pairsTo(calls, pushResult(calls, done, isError))
  ensures (|pushResult(calls, done, isError)| == (|done| + 1))
  ensures ((|pushResult(calls, done, isError)| == |calls|) ==> pairs(calls, pushResult(calls, done, isError)))
{
  PairsToSnoc(calls, done, isError);
  if |done| + 1 == |calls| {
    PairsToPairs(calls, pushResult(calls, done, isError));
  }
}

function fillRest(calls: seq<TToolCall>, done: seq<TToolResult>): seq<TToolResult>
  requires (|done| <= |calls|)
  decreases (|calls| - |done|)
{
  if (|done| == |calls|) then
    done
  else
    fillRest(calls, (done + [TToolResult(calls[|done|].id, true)]))
}

lemma fillRest_ensures(calls: seq<TToolCall>, done: seq<TToolResult>)
  requires (|done| <= |calls|)
  decreases (|calls| - |done|)
  ensures (pairsTo(calls, done) ==> pairs(calls, fillRest(calls, done)))
{
  if |done| == |calls| {
    if pairsTo(calls, done) {
      PairsToPairs(calls, done);
    }
  } else {
    if pairsTo(calls, done) {
      PairsToSnoc(calls, done, true);
    }
    fillRest_ensures(calls, done + [TToolResult(calls[|done|].id, true)]);
  }
}

function pairsToComplete(calls: seq<TToolCall>, results: seq<TToolResult>): bool
  requires pairsTo(calls, results)
  requires (|results| == |calls|)
{
  true
}

lemma pairsToComplete_ensures(calls: seq<TToolCall>, results: seq<TToolResult>)
  requires pairsTo(calls, results)
  requires (|results| == |calls|)
  ensures pairs(calls, results)
{
  PairsToPairs(calls, results);
}

// ═══════════════════════════════════════════════════════════════════════════
// .dfy-only helpers for the session builders — statements over list append,
// which //@ specs cannot express.
// ═══════════════════════════════════════════════════════════════════════════

// Extending a consistent transcript by ONE connected, valid-last message
// preserves consistency (the single-message mirror of wfFromAppendPair).
lemma WfFromAppendOne(msgs: seq<TMsg>, m: TMsg)
  requires (|msgs| > 0)
  requires wfFrom(msgs)
  requires okAdjacent(msgs[(|msgs| - 1)], m)
  requires lastOk(m)
  ensures wfFrom(msgs + [m])
  decreases |msgs|
{
  if |msgs| == 1 {
    assert (msgs + [m])[1..] == [m];
  } else {
    assert msgs[1..][|msgs[1..]| - 1] == msgs[|msgs| - 1];
    WfFromAppendOne(msgs[1..], m);
    assert (msgs + [m])[1..] == msgs[1..] + [m];
  }
}

// Answering the next unanswered call keeps the partial result block paired.
lemma PairsToSnoc(calls: seq<TToolCall>, done: seq<TToolResult>, isError: bool)
  requires pairsTo(calls, done)
  requires (|done| < |calls|)
  ensures pairsTo(calls, done + [TToolResult(calls[|done|].id, isError)])
  decreases |done|
{
  var r := TToolResult(calls[|done|].id, isError);
  if |done| == 0 {
    assert (done + [r])[0] == r;
    assert (done + [r])[1..] == [];
  } else {
    PairsToSnoc(calls[1..], done[1..], isError);
    assert calls[1..][|done[1..]|].id == calls[|done|].id;
    assert (done + [r])[1..] == done[1..] + [r];
  }
}

// A complete partial pairing IS the full pairing (pairsTo at full length = pairs).
lemma PairsToPairs(calls: seq<TToolCall>, results: seq<TToolResult>)
  requires pairsTo(calls, results)
  requires (|results| == |calls|)
  ensures pairs(calls, results)
  decreases |calls|
{
  if |calls| == 0 {
  } else {
    PairsToPairs(calls[1..], results[1..]);
  }
}
