// Generated by lsc from transcript.ts

datatype TToolCall = TToolCall(id: string, name: string)

datatype TToolResult = TToolResult(toolCallId: string, isError: bool)

datatype TMsg = user | assistant(toolCalls: seq<TToolCall>) | tool(toolResults: seq<TToolResult>)

function pairs(calls: seq<TToolCall>, results: seq<TToolResult>): bool
  decreases |calls|
{
  if (|results| != |calls|) then
    false
  else
    ((|calls| == 0) || (if (results[0].toolCallId != calls[0].id) then false else pairs(calls[1..], results[1..])))
}

function makeResults(calls: seq<TToolCall>): seq<TToolResult>
  decreases |calls|
{
  if (|calls| == 0) then
    []
  else
    ([TToolResult(calls[0].id, false)] + makeResults(calls[1..]))
}

lemma makeResults_ensures(calls: seq<TToolCall>)
  ensures (|makeResults(calls)| == |calls|)
  ensures pairs(calls, makeResults(calls))
{
}

function headOk(m: TMsg): bool
{
  (!m.tool?)
}

function lastOk(m: TMsg): bool
{
  match m {
    case assistant(i_m_toolCalls) =>
      (|i_m_toolCalls| == 0)
    case _ =>
      true
  }
}

function okAdjacent(a: TMsg, b: TMsg): bool
{
  match a {
    case assistant(i_a_toolCalls) =>
      if (|i_a_toolCalls| > 0) then
        match b {
          case tool(i_b_toolResults) =>
            pairs(i_a_toolCalls, i_b_toolResults)
          case _ =>
            false
        }
      else
        (!b.tool?)
    case _ =>
      (!b.tool?)
  }
}

function wfFrom(msgs: seq<TMsg>): bool
  decreases |msgs|
{
  ((|msgs| == 0) || (if (|msgs| == 1) then lastOk(msgs[0]) else (okAdjacent(msgs[0], msgs[1]) && wfFrom(msgs[1..]))))
}

function wellFormed(msgs: seq<TMsg>): bool
{
  ((|msgs| == 0) || (headOk(msgs[0]) && wfFrom(msgs)))
}

// ═══════════════════════════════════════════════════════════════════════════
// Proof additions (added in .dfy, additions-only over .dfy.gen).
// T1 pairing is makeResults_ensures above (auto-discharged).
// ═══════════════════════════════════════════════════════════════════════════

// A consistent sequence has a valid last message.
lemma WfFromImpliesLastOk(msgs: seq<TMsg>)
  requires |msgs| > 0
  requires wfFrom(msgs)
  ensures lastOk(msgs[|msgs| - 1])
  decreases |msgs|
{
  if |msgs| == 1 {
  } else {
    WfFromImpliesLastOk(msgs[1..]);
    assert msgs[1..][|msgs[1..]| - 1] == msgs[|msgs| - 1];
  }
}

// Core induction: extend a consistent sequence by a connected (a, t) pair where
// t is a valid last — consistency is preserved.
lemma WfFromAppendPair(msgs: seq<TMsg>, a: TMsg, t: TMsg)
  requires |msgs| > 0
  requires wfFrom(msgs)
  requires okAdjacent(msgs[|msgs| - 1], a)
  requires okAdjacent(a, t)
  requires lastOk(t)
  ensures wfFrom(msgs + [a, t])
  decreases |msgs|
{
  if |msgs| == 1 {
    assert (msgs + [a, t])[1..] == [a, t];
  } else {
    assert msgs[1..][|msgs[1..]| - 1] == msgs[|msgs| - 1];
    WfFromAppendPair(msgs[1..], a, t);
    assert (msgs + [a, t])[1..] == msgs[1..] + [a, t];
  }
}

// ── T2: appending a tool-result block preserves well-formedness ──────────────
// No orphan tool_result can be sent, and no tool_use is left unanswered.
lemma T2_AppendPreservesWellFormed(msgs: seq<TMsg>, calls: seq<TToolCall>)
  requires wellFormed(msgs)
  requires |calls| > 0
  ensures wellFormed(msgs + [assistant(calls), tool(makeResults(calls))])
{
  var a := assistant(calls);
  var t := tool(makeResults(calls));
  makeResults_ensures(calls);
  assert okAdjacent(a, t);
  assert lastOk(t);
  if |msgs| == 0 {
    assert msgs + [a, t] == [a, t];
    assert (msgs + [a, t])[1..] == [t];
  } else {
    WfFromImpliesLastOk(msgs);
    assert okAdjacent(msgs[|msgs| - 1], a);
    WfFromAppendPair(msgs, a, t);
    assert (msgs + [a, t])[0] == msgs[0];
  }
}
